// Generated by scripts/write-methodology-assets.mjs; edit pageMethodologies.js.
const contentUrl = new URL('../content/page-methodologies.json', import.meta.url).href;

export const ACCOUNT_MANAGERS_METHODOLOGY = {
  "title": "Account Managers",
  "description": "How Account coverage, manager priority, GROUP propagation, notes, and synchronization work.",
  contentUrl, "contentKey": "ACCOUNT_MANAGERS_METHODOLOGY"
};

export const BROKER_METHODOLOGIES = {
  "commissions": {
    "title": "Broker Commissions",
    "description": "How FCOS scopes commission records, applies exchange rates, and produces reports.",
    contentUrl, "contentKey": "BROKER_METHODOLOGIES:commissions"
  },
  "archive": {
    "title": "Report Archive",
    "description": "How generated reports are retained, filtered, and downloaded.",
    contentUrl, "contentKey": "BROKER_METHODOLOGIES:archive"
  },
  "configuration": {
    "title": "Broker Commission Configuration",
    "description": "How the company exchange-rate provider is controlled and applied.",
    contentUrl, "contentKey": "BROKER_METHODOLOGIES:configuration"
  }
};

export const CASHFLOW_FORECAST_METHODOLOGY = {
  "title": "Cashflow Forecast",
  "description": "How Salesforce receivables and payables become expected daily cash movement.",
  contentUrl, "contentKey": "CASHFLOW_FORECAST_METHODOLOGY"
};

export const DASHBOARD_METHODOLOGY = {
  "title": "Dashboard",
  "description": "How FCOS builds a complete, currency-safe decision view from Salesforce.",
  contentUrl, "contentKey": "DASHBOARD_METHODOLOGY"
};

export const DISPUTE_WORKFLOW_METHODOLOGY = {
  "title": "Dispute Workflow",
  "description": "How FCOS identifies parties, coordinates decisions, settles instructions, and closes a dispute.",
  contentUrl, "contentKey": "DISPUTE_WORKFLOW_METHODOLOGY"
};

export const EMAIL_ROUTER_METHODOLOGY = {
  "title": "Email Router",
  "description": "How FCOS retrieves messages and submits controlled Microsoft Graph mailbox actions.",
  contentUrl, "contentKey": "EMAIL_ROUTER_METHODOLOGY"
};

export const EXCEPTION_REVIEW_METHODOLOGY = {
  "title": "Exception Review",
  "description": "How FCOS identifies finance exceptions and coordinates their resolution.",
  contentUrl, "contentKey": "EXCEPTION_REVIEW_METHODOLOGY"
};

export const FCOS_IMPROVEMENTS_METHODOLOGY = {
  "title": "FCOS Improvements",
  "description": "How bugs and feature requests are reported, discussed, approved, and resolved.",
  contentUrl, "contentKey": "FCOS_IMPROVEMENTS_METHODOLOGY"
};

export const GROWTH_COACHING_METHODOLOGY = {
  "title": "Growth & Coaching",
  "description": "How FCOS separates accountable development from private, equal-participant coaching.",
  contentUrl, "contentKey": "GROWTH_COACHING_METHODOLOGY"
};

export const MASTER_CONTRACTS_METHODOLOGY = {
  "title": "Master Contracts methodology",
  "description": "How FCOS preserves approved Master Contract baselines while Salesforce operates each generated delivery.",
  contentUrl, "contentKey": "MASTER_CONTRACTS_METHODOLOGY"
};

export const MY_COMMITMENTS_METHODOLOGY = {
  "title": "My Commitments",
  "description": "How FCOS combines personal work and determines urgency.",
  contentUrl, "contentKey": "MY_COMMITMENTS_METHODOLOGY"
};

export const PAYMENT_COLLECTIONS_METHODOLOGIES = {
  "collections": {
    "title": "Payment Collections",
    "description": "How FCOS prioritizes buyer collection work and controls external reminders.",
    contentUrl, "contentKey": "PAYMENT_COLLECTIONS_METHODOLOGIES:collections"
  },
  "incoming": {
    "title": "Incoming Payments",
    "description": "How received-payment records are connected to collection work.",
    contentUrl, "contentKey": "PAYMENT_COLLECTIONS_METHODOLOGIES:incoming"
  },
  "reconciliation": {
    "title": "Reconciliation Exceptions",
    "description": "How FCOS compares collection state with live Salesforce balances and payments.",
    contentUrl, "contentKey": "PAYMENT_COLLECTIONS_METHODOLOGIES:reconciliation"
  },
  "legacy": {
    "title": "Legacy settled data",
    "description": "A privileged, read-only audit of incomplete Salesforce payment evidence before the FCOS cutover.",
    contentUrl, "contentKey": "PAYMENT_COLLECTIONS_METHODOLOGIES:legacy"
  },
  "variable-charges": {
    "title": "Variable Charges",
    "description": "How each supplier’s costs and buyer charges are reviewed side by side with independent invoice gates.",
    contentUrl, "contentKey": "PAYMENT_COLLECTIONS_METHODOLOGIES:variable-charges"
  }
};

export const PROJECTS_TASKS_METHODOLOGY = {
  "title": "Projects & Tasks",
  "description": "How shared work, authority, progress, notifications, dependencies, and private files operate.",
  contentUrl, "contentKey": "PROJECTS_TASKS_METHODOLOGY"
};

export const QLIK_VALIDATOR_METHODOLOGY = {
  "title": "Dashboard and Qlik Validator Tool",
  "description": "How FCOS selects STEMs and compares calculated profit with Qlik values.",
  contentUrl, "contentKey": "QLIK_VALIDATOR_METHODOLOGY"
};

export const SETTINGS_METHODOLOGIES = {
  "my": {
    "title": "My Settings",
    "description": "How personal FCOS workspace preferences are synchronized and applied.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:my"
  },
  "people": {
    "title": "People & Access",
    "description": "How FCOS users, permissions, capabilities, and reporting lines are controlled.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:people"
  },
  "email-delivery": {
    "title": "Email Delivery",
    "description": "How Microsoft Graph mailboxes are registered and assigned to FCOS email purposes.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:email-delivery"
  },
  "finance": {
    "title": "Finance",
    "description": "How the company financing rate controls Dashboard EBIT calculations.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:finance"
  },
  "ai": {
    "title": "AI Models",
    "description": "How FCOS selects models and reports usage without weakening workflow permissions.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:ai"
  },
  "updates": {
    "title": "FCOS Updates",
    "description": "How release changes are prepared and sent as controlled internal communications.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:updates"
  },
  "health": {
    "title": "System Health",
    "description": "How live service status and provider monitoring should be interpreted.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:health"
  },
  "audit": {
    "title": "Audit Trail",
    "description": "How FCOS presents redacted operational and security history.",
    contentUrl, "contentKey": "SETTINGS_METHODOLOGIES:audit"
  }
};

export const SPECIAL_TERMS_METHODOLOGY = {
  "title": "Special Terms",
  "description": "How FCOS manages authoritative Salesforce wording and matching rules.",
  contentUrl, "contentKey": "SPECIAL_TERMS_METHODOLOGY"
};

export const UNOFFICIAL_COMPENSATION_METHODOLOGY = {
  "title": "Unofficial Compensation",
  "description": "How FCOS combines Salesforce claims and recoveries and controls compensation changes.",
  contentUrl, "contentKey": "UNOFFICIAL_COMPENSATION_METHODOLOGY"
};
