export const WORKSPACE_VIEW_LABELS = Object.freeze({
  needs_action: 'Needs Action',
  all: 'All Records',
  open: 'All Open',
  closed: 'Closed / Settled',
  exceptions: 'Exceptions',
  activity: 'Activity',
  methodology: 'Methodology',
});

export const WORKSPACE_STANDARDS = Object.freeze({
  my_commitments: {
    title: 'My Commitments',
    route: '/my-commitments',
    section: 'Personal',
    authority: 'Source workflows',
    views: ['needs_action', 'all'],
    freshness: 'Live workflow state',
    consequentialActionsRefresh: true,
  },
  growth_coaching: {
    title: 'Growth & Coaching',
    route: '/growth-coaching',
    section: 'Personal',
    authority: 'FCOS',
    views: ['needs_action', 'all', 'activity'],
    freshness: 'Live FCOS state',
    consequentialActionsRefresh: true,
  },
  projects_tasks: {
    title: 'Projects & Tasks',
    route: '/projects-tasks',
    section: 'Personal',
    authority: 'FCOS',
    views: ['needs_action', 'all', 'activity'],
    freshness: 'Live FCOS state',
    consequentialActionsRefresh: true,
  },
  fcos_improvements: {
    title: 'FCOS Improvements',
    route: '/fcos-improvements',
    section: 'Personal',
    authority: 'FCOS with General Manager approval',
    views: ['needs_action', 'all', 'closed', 'activity'],
    freshness: 'Live FCOS state',
    consequentialActionsRefresh: true,
  },
  dashboard: {
    title: 'Dashboard',
    route: '/',
    section: 'Trading',
    authority: 'Salesforce',
    views: ['all', 'exceptions'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: false,
  },
  buyers_administrator: {
    title: 'Account Managers',
    route: '/account-managers',
    section: 'Trading',
    authority: 'Salesforce Accounts with FCOS assignments',
    views: ['all'],
    freshness: 'Live assignments with short Salesforce reference cache',
    consequentialActionsRefresh: true,
  },
  master_contracts: {
    title: 'Master Contracts',
    route: '/master-contracts',
    section: 'Trading',
    authority: 'FCOS approved terms with live Salesforce operational reconciliation',
    views: ['all', 'exceptions', 'activity'],
    freshness: 'Live on open with hourly Salesforce reconciliation',
    consequentialActionsRefresh: true,
  },
  markets: {
    title: 'Markets',
    route: '/markets',
    section: 'Trading',
    authority: 'Licensed market reports and controlled FCOS MOPS records',
    views: ['delivered', 'cargo-forward', 'signals'],
    freshness: 'Live service-only market observations',
    consequentialActionsRefresh: true,
  },
  special_terms: {
    title: 'Special Terms',
    route: '/special-terms',
    section: 'Trading',
    authority: 'Salesforce',
    views: ['all', 'activity'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: true,
  },
  hedge_desk: {
    title: 'Hedge Desk',
    route: '/hedge-desk',
    section: 'Trading',
    authority: 'FCOS Hedge Desk with Salesforce settlement links',
    views: ['needs_action', 'all', 'exceptions', 'activity'],
    freshness: 'Live FCOS state; Salesforce refreshed before synchronization',
    consequentialActionsRefresh: true,
  },
  payment_collections: {
    title: 'Payment Collections',
    route: '/payment-collections',
    section: 'Cross Functions',
    authority: 'Salesforce receivables and ship-agent charges with FCOS workflow state',
    views: ['needs_action', 'open', 'closed', 'exceptions', 'activity'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: true,
  },
  disputes: {
    title: 'Dispute Workflow',
    route: '/disputes',
    section: 'Cross Functions',
    authority: 'Salesforce STEM status with FCOS workflow state',
    views: ['needs_action', 'all', 'closed', 'exceptions', 'activity'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: true,
  },
  unofficial_compensation: {
    title: 'Unofficial Compensation',
    route: '/unofficial-compensation',
    section: 'Cross Functions',
    authority: 'Salesforce',
    views: ['needs_action', 'closed', 'exceptions', 'activity'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: true,
  },
  brokers: {
    title: 'Broker Commissions',
    route: '/brokers',
    section: 'Cross Functions',
    authority: 'Salesforce with FCOS report archive',
    views: ['needs_action', 'all', 'exceptions', 'activity'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: true,
  },
  cashflow_forecast: {
    title: 'Cashflow',
    route: '/cashflow-forecast',
    section: 'Finance',
    authority: 'Salesforce',
    views: ['all', 'exceptions'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: false,
  },
  email_router: {
    title: 'Email Router',
    route: '/email-router',
    section: 'Tools',
    authority: 'Microsoft Graph with FCOS routing configuration',
    views: ['needs_action', 'all', 'exceptions', 'activity'],
    freshness: 'Graph delta state with live action validation',
    consequentialActionsRefresh: true,
  },
  review: {
    title: 'Exception Review',
    route: '/review',
    section: 'Tools',
    authority: 'Salesforce',
    views: ['needs_action', 'all', 'exceptions'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: false,
  },
  pnl: {
    title: 'Qlik Validator',
    route: '/pnl',
    section: 'Tools',
    authority: 'Salesforce compared with uploaded Qlik data',
    views: ['all', 'exceptions'],
    freshness: 'Short Salesforce snapshot',
    consequentialActionsRefresh: false,
  },
});

export function workspaceStandard(id) {
  return WORKSPACE_STANDARDS[id] || null;
}

export function workspaceNavigation(id, overrides = {}) {
  const standard = workspaceStandard(id);
  if (!standard) throw new Error(`Unknown workspace standard: ${id}`);
  return {
    id,
    to: standard.route,
    label: standard.title,
    ...overrides,
  };
}
