export const XERO_PORTAL_MANUAL_LANGUAGES = Object.freeze([
  { id: 'en', label: 'English' },
  { id: 'zh-Hant', label: '繁體中文' },
]);

export const XERO_PORTAL_MANUALS = Object.freeze({
  en: {
    title: 'Xero Portal User Manual',
    subtitle: 'A detailed guide to connection management, contact maintenance, accounting migration, receipts, and audit records.',
    importantTitle: 'Before you start',
    important: [
      'Salesforce is the source for FCOS operational and financial documents. Xero receives accounting transactions only through reviewed workflows.',
      'A read-only preview never changes Xero. A button marked as a Xero write changes the connected Xero organisation and is protected by permissions, review confirmation, and the external-action gate.',
      'Do not approve a Product, tax, bank, document, or payment mapping unless the accounting treatment has been confirmed by Finance.',
    ],
    effectLabels: {
      read: 'Read only',
      fcos: 'FCOS save',
      xero: 'Xero write',
      navigation: 'Navigation',
    },
    workflowTitle: 'Recommended workflow',
    workflow: [
      ['1', 'Check connection', 'Confirm the organisation, scopes, Salesforce source, and write-gate badges before starting.'],
      ['2', 'Maintain contacts', 'Preview proposed renames or archives, review evidence, select eligible rows, then apply only approved changes.'],
      ['3', 'Approve mappings', 'In Accounting Sync, review suggested Buyer and Supplier Product mappings and map DBS/UBS to the correct Xero bank accounts.'],
      ['4', 'Build accounting preview', 'Classify all Salesforce documents from the cutoff date. Resolve blocked rows and rerun until the intended records are eligible or protected.'],
      ['5', 'Authorise and run', 'Finance selects eligible documents, confirms review, authorises the batch, and only then runs the guarded Xero write.'],
      ['6', 'Apply exact payments', 'Preview payment allocations after documents are authorised, review exact matches, and apply only eligible payments.'],
    ],
    sections: [
      {
        id: 'connection',
        title: '1. Connection and page header',
        purpose: 'Use the header and four status panels to confirm which Xero organisation is connected, which OAuth scopes are available, which Salesforce source is active, and whether external writes are enabled.',
        steps: [
          'Check the Connected badge and Xero tenant organisation before doing any review.',
          'Check Xero scopes. Contacts, invoices, attachments, payments, and accounting settings are enabled separately.',
          'Treat “Xero writes gated” as a safety lock: previews remain available, but guarded financial or contact writes cannot run.',
        ],
        controls: [
          ['User manual', 'Opens this bilingual manual. Use the language selector at the top to switch languages.', 'Always available inside Xero Portal.', 'navigation'],
          ['Refresh', 'Reloads connection status, receipts, the latest contact lifecycle run, and the latest automatic-contact run.', 'Disabled while another page-level action is running.', 'read'],
          ['Connect Xero', 'Starts Xero OAuth and returns to FCOS after the organisation is authorised.', 'Shown when disconnected and enabled only when the Xero app is configured.', 'fcos'],
          ['Reconnect scopes', 'Runs OAuth again without first deleting the stored connection, so missing accounting or payment scopes can be granted.', 'Shown only when connected but required financial scopes are missing.', 'fcos'],
          ['Disconnect', 'Removes the stored FCOS connection to the Xero tenant. It does not delete Xero contacts or transactions.', 'Shown when connected.', 'fcos'],
          ['Contacts / Accounting Sync / Receipts / Auto-Created Contacts / User Manual', 'Switches workspace sections without performing a data write.', 'Always available; individual actions inside a tab can still be permission-gated.', 'navigation'],
        ],
      },
      {
        id: 'contacts',
        title: '2. Contacts: review, rename, and archive',
        purpose: 'Compare Xero contacts with exact Salesforce Account names and CL Keys. FCOS proposes actions; users must review and explicitly select every Xero change.',
        steps: [
          'Choose the usage refresh depth. Use the cached/default scan normally; use incremental or full refresh only when current usage evidence is required.',
          'Click Preview. Review KPI totals, usage coverage, status explanations, estimated Xero calls, and every proposed row.',
          'Use search and filters to narrow the table. Only Eligible Rename or Archive rows can be selected.',
          'Select approved rows, tick Reviewed, and click Apply selected.',
          'Download JSON or CSV audit evidence when a review record is required.',
        ],
        controls: [
          ['Show unmatched Xero', 'Shows active Xero contacts that do not have a confirmed Salesforce Account match. Click again as Show all rows to remove the filter.', 'Available after the page loads.', 'navigation'],
          ['Preview', 'Reads Xero contacts and Salesforce Accounts, evaluates name/CL Key matches and usage, and prepares proposed actions. It does not rename or archive anything.', 'Requires a Xero connection and Contacts scope.', 'read'],
          ['Full usage refresh', 'Re-reads every supported Xero usage source before classifying unused contacts. It is slower and consumes more Xero calls.', 'Select before Preview. Selecting it disables Incremental usage refresh.', 'read'],
          ['Incremental usage refresh', 'Refreshes only usage evidence that can be updated incrementally, reducing calls compared with a full scan.', 'Select before Preview; unavailable while Full usage refresh is selected.', 'read'],
          ['JSON audit', 'Downloads the complete lifecycle run, including summary and row evidence, as JSON.', 'Enabled after a Preview exists.', 'read'],
          ['CSV audit', 'Downloads lifecycle rows as a spreadsheet-friendly CSV file.', 'Enabled after a Preview exists.', 'read'],
          ['Search Xero, Salesforce, CL Key', 'Filters the loaded rows by visible Xero and Salesforce identities, CL Key, Account ID, or reason.', 'Available after a Preview; does not rerun the scan.', 'navigation'],
          ['Action / Status / Reason filters', 'Filters the loaded result by proposed action, workflow status, or classification reason.', 'Available after a Preview.', 'navigation'],
          ['Row Use checkbox', 'Selects one eligible Rename or Archive row for the pending batch. Blocked, Keep, or Exception rows cannot be selected.', 'Enabled only for eligible rows.', 'navigation'],
          ['Select visible eligible', 'Selects all eligible rows currently included by the active filters. Existing selections outside the visible filter are replaced.', 'Enabled when at least one visible row is eligible.', 'navigation'],
          ['Clear', 'Clears all selected contact rows.', 'Always available.', 'navigation'],
          ['Reviewed', 'Confirms that the selected rows and evidence have been reviewed. It is a required acknowledgement, not an action by itself.', 'Tick after review and before Apply selected.', 'navigation'],
          ['Apply selected', 'Renames or archives the selected Xero contacts, then verifies and records the result.', 'Requires a Preview, Reviewed confirmation, at least one visible eligible selection, permission, and the contact-write gate.', 'xero'],
        ],
      },
      {
        id: 'accounting',
        title: '3. Accounting Sync: Salesforce-to-Xero cutover',
        purpose: 'Classify Salesforce Buyer Invoices, Supplier Bills, and Credit Notes from the accounting cutoff; create or safely update Xero records only after Finance mapping, review, and authorisation.',
        steps: [
          'Set the accounting cutoff. The current cutover starts at 1 January 2026.',
          'Click Build read-only preview. Review legacy mapping suggestions and conflicts.',
          'Approve Buyer and Supplier Product account/tax mappings separately. Approve DBS and UBS bank mappings before payment work.',
          'Build the preview again after mapping changes. Review eligible, protected, and blocked classifications plus control totals.',
          'Select eligible documents, tick Finance reviewed, and click Authorise batch. This checkpoints the approved batch in FCOS but does not post it yet.',
          'When the financial write gate is enabled, click Run selected. Recheck the result before previewing payments.',
          'Click Preview payments, review exact allocations, tick Finance reviewed payments, then apply only eligible payments.',
        ],
        controls: [
          ['Accounting cutoff', 'Sets the earliest Salesforce invoice date included in the document preview.', 'Cannot be earlier than 1 January 2026.', 'navigation'],
          ['Mappings', 'Reloads saved Product and bank mappings plus current Xero Chart of Accounts options.', 'Available while no accounting action is running.', 'read'],
          ['Build read-only preview', 'Reads Salesforce and Xero, classifies each document, calculates control totals, and derives legacy mapping suggestions. No Xero transaction is changed.', 'Requires Xero connection plus Contacts, Invoices, and Accounting settings scopes.', 'read'],
          ['Product mapping Previous / Next', 'Moves through pages of Buyer and Supplier Product mapping rows. Suggestions and conflicts are shown first.', 'Available when the preview has loaded Products.', 'navigation'],
          ['Xero account selector', 'Chooses the Xero revenue or cost account for one exact Salesforce Product and direction.', 'Finance must confirm the accounting treatment.', 'navigation'],
          ['Tax type selector', 'Chooses the Xero tax treatment for that Product/direction. NONE is the default but must still be reviewed.', 'Finance must confirm the tax treatment.', 'navigation'],
          ['Approve mapping', 'Saves the selected Product/direction account and tax mapping in FCOS. It does not create or modify a Xero invoice.', 'Requires a selected Xero account and mapping permission.', 'fcos'],
          ['Update approval', 'Replaces an existing approved Product mapping with the newly selected account/tax treatment.', 'Shown for an already saved mapping; rerun the preview afterward.', 'fcos'],
          ['DBS / UBS bank Save icon', 'Maps the Salesforce bank name to one Xero bank account for exact payment allocation.', 'Requires a selected Xero bank account.', 'fcos'],
          ['Select eligible', 'Selects all currently eligible accounting documents in the loaded preview.', 'Available after a Preview.', 'navigation'],
          ['Clear', 'Clears all selected accounting documents.', 'Available after a Preview.', 'navigation'],
          ['Finance reviewed', 'Records the reviewer acknowledgement required before authorising the selected document batch.', 'Tick only after checking identities, dates, currencies, totals, actions, and blockers.', 'navigation'],
          ['Authorise batch', 'Freezes the reviewed FCOS selection and fingerprints for the guarded run. It does not yet write the selected documents to Xero.', 'Requires Ready for review status, Finance reviewed, and at least one selection.', 'fcos'],
          ['Run selected', 'Creates Xero drafts, updates safely editable matches, or links exact matches according to the authorised classification.', 'Shown after authorisation/partial failure and enabled only when the financial write gate is enabled.', 'xero'],
          ['Document Previous / Next', 'Moves through pages of classified Salesforce documents without changing the selection.', 'Available after a Preview.', 'navigation'],
          ['Xero document link', 'Opens the matched Xero invoice, bill, or credit note in a new tab.', 'Shown when a Xero match exists.', 'navigation'],
          ['Preview payments', 'Classifies Salesforce Receivable and Payable payments against authorised Xero documents and saved bank mappings. It performs no payment write.', 'Use only after document processing and bank mapping are complete.', 'read'],
          ['Payment Use checkbox', 'Selects one exact eligible payment allocation.', 'Enabled only for exact payment_apply rows.', 'navigation'],
          ['Finance reviewed payments', 'Confirms Finance reviewed the selected payment dates, amounts, currencies, banks, and invoice allocations.', 'Required before Apply exact payments.', 'navigation'],
          ['Apply exact payments', 'Creates only the selected exact Xero payment allocations. Ambiguous remittances, deposits, bank charges, write-offs, and unsupported cases stay blocked.', 'Requires selections, review confirmation, bank mappings, authorised documents, permission, and the financial write gate.', 'xero'],
          ['Payment Previous / Next', 'Moves through pages of payment classifications.', 'Available after Preview payments.', 'navigation'],
        ],
      },
      {
        id: 'receipts',
        title: '4. Receipts: capture and draft bills',
        purpose: 'Upload a receipt, review extracted fields, store it in FCOS, and optionally create an ACCPAY draft bill in Xero with the original file attached.',
        steps: [
          'Choose an image or PDF up to the permitted file-size limit.',
          'For an image, run OCR and then verify every extracted field. Enter PDF details manually.',
          'Confirm Merchant, Date, Total, Currency, Account, Tax, Category, and Notes.',
          'Use Save draft to retain the receipt in FCOS, or Create Xero draft bill to save and immediately sync it.',
          'Use Sync in Receipt Audit for a previously saved receipt. Open Draft bill to inspect the Xero result.',
        ],
        controls: [
          ['Choose file', 'Selects an image or PDF receipt. The file is not uploaded until Save draft or Create Xero draft bill is clicked.', 'Required for saving or syncing.', 'navigation'],
          ['OCR image', 'Runs browser-based English OCR on an image and fills the editable receipt fields and OCR notes. Always verify the result.', 'Enabled for a selected file; PDFs require manual entry.', 'read'],
          ['Reset', 'Clears the editable receipt fields. It does not delete a previously saved receipt.', 'Always available.', 'navigation'],
          ['Save draft', 'Stores the receipt file and reviewed fields in FCOS without creating a Xero transaction.', 'Requires a selected file and receipt-management permission.', 'fcos'],
          ['Create Xero draft bill', 'Stores the receipt, creates an ACCPAY draft bill in Xero, and attaches the original file.', 'Requires a file, Xero connection, Invoices and Attachments scopes, and permission.', 'xero'],
          ['Sync', 'Creates and attaches the Xero draft bill for an existing FCOS receipt that has not yet synced.', 'Disabled after successful sync or when Xero/scopes are unavailable.', 'xero'],
          ['Draft bill link', 'Opens the created Xero draft bill in a new browser tab.', 'Shown after successful sync.', 'navigation'],
        ],
      },
      {
        id: 'automation',
        title: '5. Auto-Created Contacts audit',
        purpose: 'Review signed Salesforce events that asked FCOS to create a missing Xero contact. This page is an audit view; it does not manually trigger contact creation.',
        steps: [
          'Review Pending, Created, Already exists, and Failed totals.',
          'Inspect the exact Salesforce Account, Xero Contact, match basis, and reason.',
          'Download audit evidence when required for investigation or control review.',
        ],
        controls: [
          ['JSON audit', 'Downloads the complete latest automatic-contact run as JSON.', 'Enabled when an automation run exists.', 'read'],
          ['CSV audit', 'Downloads the latest automatic-contact rows as CSV.', 'Enabled when an automation run exists.', 'read'],
        ],
      },
      {
        id: 'statuses',
        title: '6. Statuses, safeguards, and troubleshooting',
        purpose: 'Use the first blocking reason shown in each table as the required next action. FCOS fails closed when identity, mapping, scope, review, rate-limit, or financial evidence is incomplete.',
        steps: [
          'Eligible means the row can be selected under the current evidence and permissions.',
          'Protected legacy means FCOS found historical Xero accounting that must not be rewritten automatically.',
          'Blocked or Exception means the displayed reason must be resolved or retained as a controlled exception.',
          'If a control is disabled, check connection, OAuth scopes, your FCOS capability, review acknowledgement, selected rows, mapping completeness, and the external-action gate.',
          'After a stale-write or changed-source error, Refresh and rebuild the Preview; do not repeatedly submit the old batch.',
          'A failed Xero request remains checkpointed. Correct the reason and resume the guarded run rather than creating a new duplicate transaction.',
        ],
        controls: [],
      },
    ],
  },
  'zh-Hant': {
    title: 'Xero Portal 使用手冊',
    subtitle: '詳細說明連線管理、聯絡人維護、會計遷移、收據及審計紀錄。',
    importantTitle: '開始前須知',
    important: [
      'Salesforce 是 FCOS 營運及財務文件的資料來源。Xero 只會透過已覆核的流程接收會計交易。',
      '「唯讀預覽」絕不會更改 Xero。標示為「寫入 Xero」的按鈕會更改已連接的 Xero 機構，並受權限、覆核確認及外部操作閘門保護。',
      '在財務部確認會計處理前，切勿核准任何產品、稅項、銀行、文件或付款對應。',
    ],
    effectLabels: {
      read: '唯讀',
      fcos: '儲存至 FCOS',
      xero: '寫入 Xero',
      navigation: '導覽／篩選',
    },
    workflowTitle: '建議工作流程',
    workflow: [
      ['1', '檢查連線', '開始前確認機構、授權範圍、Salesforce 來源及寫入閘門標籤。'],
      ['2', '維護聯絡人', '預覽建議的重新命名或封存，覆核證據，選取合資格項目，然後只套用已核准的更改。'],
      ['3', '核准對應設定', '在「Accounting Sync」分別覆核買方及供應商產品對應，並把 DBS／UBS 對應至正確的 Xero 銀行帳戶。'],
      ['4', '建立會計預覽', '分類由截數日起的所有 Salesforce 文件。先處理被封鎖項目，再重新預覽，直至文件成為合資格或受保護項目。'],
      ['5', '授權及執行', '財務部選取合資格文件、確認已覆核、授權批次，最後才執行受保護的 Xero 寫入。'],
      ['6', '套用精確付款', '文件獲授權後預覽付款分配，覆核精確配對，並只套用合資格付款。'],
    ],
    sections: [
      {
        id: 'connection',
        title: '1. 連線及頁首',
        purpose: '利用頁首及四個狀態面板，確認已連接的 Xero 機構、OAuth 授權範圍、Salesforce 來源及外部寫入是否已啟用。',
        steps: [
          '進行任何覆核前，先檢查「Connected」標籤及 Xero tenant 的機構名稱。',
          '檢查 Xero scopes。聯絡人、發票、附件、付款及會計設定會分開授權。',
          '「Xero writes gated」代表安全鎖已啟用：仍可預覽，但不可執行受保護的財務或聯絡人寫入。',
        ],
        controls: [
          ['User manual', '開啟本雙語手冊。可用頁頂的語言選擇器切換語言。', '在 Xero Portal 內隨時可用。', 'navigation'],
          ['Refresh', '重新載入連線狀態、收據、最新聯絡人生命週期批次及最新自動建立聯絡人批次。', '其他頁面操作進行時會停用。', 'read'],
          ['Connect Xero', '開始 Xero OAuth 授權，完成機構授權後返回 FCOS。', '未連線時顯示；只在 Xero 應用程式已設定時啟用。', 'fcos'],
          ['Reconnect scopes', '無須先刪除現有連線便可再次進行 OAuth，以補充會計或付款授權範圍。', '已連線但缺少所需財務範圍時才顯示。', 'fcos'],
          ['Disconnect', '移除 FCOS 儲存的 Xero tenant 連線；不會刪除 Xero 聯絡人或交易。', '已連線時顯示。', 'fcos'],
          ['Contacts / Accounting Sync / Receipts / Auto-Created Contacts / User Manual', '切換工作區，不會寫入資料。每個分頁內的操作仍可能受權限限制。', '一直可用。', 'navigation'],
        ],
      },
      {
        id: 'contacts',
        title: '2. Contacts：覆核、重新命名及封存',
        purpose: '按 Salesforce Account 的準確名稱及 CL Key 比對 Xero 聯絡人。FCOS 只會提出建議；使用者必須覆核並明確選取每項 Xero 更改。',
        steps: [
          '選擇使用紀錄更新程度。一般使用快取／預設掃描；只有需要最新使用證據時才使用增量或完整更新。',
          '按 Preview，覆核 KPI、使用範圍、狀態說明、預計 Xero API 次數及每一建議項目。',
          '用搜尋及篩選收窄結果。只有 Eligible 的 Rename 或 Archive 項目可選取。',
          '選取已核准項目，勾選 Reviewed，再按 Apply selected。',
          '如需保留覆核紀錄，可下載 JSON 或 CSV 審計檔案。',
        ],
        controls: [
          ['Show unmatched Xero', '只顯示沒有已確認 Salesforce Account 配對的現行 Xero 聯絡人。再次按下「Show all rows」可取消篩選。', '頁面載入後可用。', 'navigation'],
          ['Preview', '讀取 Xero 聯絡人及 Salesforce Accounts，評估名稱／CL Key 配對與使用情況，並準備建議操作；不會重新命名或封存任何資料。', '需要 Xero 連線及 Contacts scope。', 'read'],
          ['Full usage refresh', '分類未使用聯絡人前，重新讀取所有受支援的 Xero 使用來源；所需時間及 API 次數較多。', 'Preview 前選取；選取後會停用 Incremental usage refresh。', 'read'],
          ['Incremental usage refresh', '只更新可增量讀取的使用證據，比完整掃描耗用較少 API 次數。', 'Preview 前選取；Full usage refresh 開啟時不可用。', 'read'],
          ['JSON audit', '以 JSON 下載完整生命週期批次，包括摘要及每行證據。', '有 Preview 後啟用。', 'read'],
          ['CSV audit', '以適合試算表的 CSV 下載生命週期項目。', '有 Preview 後啟用。', 'read'],
          ['Search Xero, Salesforce, CL Key', '按 Xero／Salesforce 身分、CL Key、Account ID 或原因篩選已載入的項目。', '有 Preview 後可用；不會重新掃描。', 'navigation'],
          ['Action / Status / Reason filters', '按建議操作、工作狀態或分類原因篩選結果。', '有 Preview 後可用。', 'navigation'],
          ['每行 Use 勾選框', '把一個合資格的 Rename 或 Archive 項目加入待處理批次；Blocked、Keep 或 Exception 不可選取。', '只在合資格項目啟用。', 'navigation'],
          ['Select visible eligible', '選取目前篩選結果內所有合資格項目；會取代篩選結果以外的既有選取。', '至少有一個可見合資格項目時啟用。', 'navigation'],
          ['Clear', '清除所有已選聯絡人項目。', '一直可用。', 'navigation'],
          ['Reviewed', '確認已覆核所選項目及證據。此勾選本身不會執行更改。', '覆核完成後、Apply selected 前勾選。', 'navigation'],
          ['Apply selected', '重新命名或封存所選 Xero 聯絡人，然後驗證並記錄結果。', '需要 Preview、Reviewed、至少一個可見合資格項目、相關權限及聯絡人寫入閘門。', 'xero'],
        ],
      },
      {
        id: 'accounting',
        title: '3. Accounting Sync：Salesforce 至 Xero 會計切換',
        purpose: '分類會計截數日起的 Salesforce Buyer Invoices、Supplier Bills 及 Credit Notes；只有完成財務對應、覆核及授權後，才建立或安全更新 Xero 紀錄。',
        steps: [
          '設定 accounting cutoff。目前切換由 2026 年 1 月 1 日開始。',
          '按 Build read-only preview，覆核舊有會計對應建議及衝突。',
          '分別核准買方及供應商的產品會計科目／稅項對應。處理付款前，核准 DBS 及 UBS 銀行帳戶對應。',
          '更改對應後重新建立預覽。覆核 eligible、protected、blocked 分類及控制總額。',
          '選取合資格文件，勾選 Finance reviewed，再按 Authorise batch。這只會在 FCOS 鎖定已核准批次，仍未過帳至 Xero。',
          '財務寫入閘門啟用後按 Run selected，並在預覽付款前再次檢查結果。',
          '按 Preview payments，覆核精確付款分配，勾選 Finance reviewed payments，然後只套用合資格付款。',
        ],
        controls: [
          ['Accounting cutoff', '設定文件預覽包含的最早 Salesforce 發票日期。', '不可早於 2026 年 1 月 1 日。', 'navigation'],
          ['Mappings', '重新載入已儲存的產品／銀行對應及目前 Xero Chart of Accounts 選項。', '沒有其他會計操作進行時可用。', 'read'],
          ['Build read-only preview', '讀取 Salesforce 及 Xero、分類每份文件、計算控制總額及產生舊有會計對應建議；不會更改任何 Xero 交易。', '需要 Xero 連線及 Contacts、Invoices、Accounting settings scopes。', 'read'],
          ['產品對應 Previous / Next', '瀏覽買方及供應商產品對應頁面；建議及衝突會優先顯示。', '預覽載入產品後可用。', 'navigation'],
          ['Xero account selector', '為一個準確 Salesforce Product 及方向選擇 Xero 收入或成本科目。', '必須由財務部確認會計處理。', 'navigation'],
          ['Tax type selector', '選擇該產品／方向的 Xero 稅項處理。預設為 NONE，但仍須覆核。', '必須由財務部確認稅務處理。', 'navigation'],
          ['Approve mapping', '把所選產品／方向的會計科目及稅項對應儲存至 FCOS；不會建立或更改 Xero 發票。', '需要選定 Xero 科目及對應設定權限。', 'fcos'],
          ['Update approval', '以新選擇的科目／稅項取代已核准的產品對應。', '已有對應時顯示；儲存後須重新預覽。', 'fcos'],
          ['DBS／UBS 銀行 Save 圖示', '把 Salesforce 銀行名稱對應至一個 Xero 銀行帳戶，以供精確付款分配。', '需要選定 Xero 銀行帳戶。', 'fcos'],
          ['Select eligible', '選取已載入預覽內所有合資格會計文件。', '有 Preview 後可用。', 'navigation'],
          ['Clear', '清除所有已選會計文件。', '有 Preview 後可用。', 'navigation'],
          ['Finance reviewed', '記錄財務覆核確認；授權文件批次前必須勾選。', '只應在核對身分、日期、貨幣、總額、操作及封鎖原因後勾選。', 'navigation'],
          ['Authorise batch', '鎖定已覆核的 FCOS 選擇及指紋，供受保護流程使用；仍未把文件寫入 Xero。', '需要 Ready for review 狀態、Finance reviewed 及至少一個選取項目。', 'fcos'],
          ['Run selected', '按已授權分類建立 Xero 草稿、更新可安全編輯的配對，或連結精確配對。', '授權／部分失敗後顯示；只有財務寫入閘門已啟用時才可執行。', 'xero'],
          ['文件 Previous / Next', '瀏覽已分類 Salesforce 文件頁面，不會改變選取。', '有 Preview 後可用。', 'navigation'],
          ['Xero 文件連結', '在新分頁開啟已配對的 Xero invoice、bill 或 credit note。', '有 Xero 配對時顯示。', 'navigation'],
          ['Preview payments', '按已授權 Xero 文件及銀行對應分類 Salesforce Receivable／Payable payments；不會寫入付款。', '只應在完成文件處理及銀行對應後使用。', 'read'],
          ['付款 Use 勾選框', '選取一項精確而合資格的付款分配。', '只在精確 payment_apply 項目啟用。', 'navigation'],
          ['Finance reviewed payments', '確認財務部已覆核所選付款日期、金額、貨幣、銀行及發票分配。', 'Apply exact payments 前必須勾選。', 'navigation'],
          ['Apply exact payments', '只建立所選精確 Xero 付款分配；含糊匯款、按金、銀行費用、撇帳及不支援項目仍會被封鎖。', '需要選取、覆核確認、銀行對應、已授權文件、權限及財務寫入閘門。', 'xero'],
          ['付款 Previous / Next', '瀏覽付款分類頁面。', 'Preview payments 後可用。', 'navigation'],
        ],
      },
      {
        id: 'receipts',
        title: '4. Receipts：擷取及草稿供應商帳單',
        purpose: '上載收據、覆核擷取欄位、儲存至 FCOS，並可選擇在 Xero 建立 ACCPAY 草稿供應商帳單及附上原檔。',
        steps: [
          '選擇符合檔案大小限制的圖片或 PDF。',
          '圖片可使用 OCR，之後必須核對每個擷取欄位；PDF 資料須手動輸入。',
          '確認 Merchant、Date、Total、Currency、Account、Tax、Category 及 Notes。',
          '使用 Save draft 只儲存於 FCOS；或使用 Create Xero draft bill 儲存並即時同步。',
          '已儲存但未同步的收據可在 Receipt Audit 使用 Sync；使用 Draft bill 連結檢查 Xero 結果。',
        ],
        controls: [
          ['Choose file', '選擇圖片或 PDF 收據。按 Save draft 或 Create Xero draft bill 前不會上載。', '儲存或同步前必須選擇。', 'navigation'],
          ['OCR image', '在瀏覽器執行英文圖片 OCR，填入可編輯收據欄位及 OCR 備註；必須人手覆核。', '選擇檔案後啟用；PDF 須手動輸入。', 'read'],
          ['Reset', '清除可編輯收據欄位；不會刪除已儲存收據。', '一直可用。', 'navigation'],
          ['Save draft', '把收據檔案及已覆核欄位儲存至 FCOS，不建立 Xero 交易。', '需要已選檔案及收據管理權限。', 'fcos'],
          ['Create Xero draft bill', '儲存收據、在 Xero 建立 ACCPAY 草稿供應商帳單，並附上原始檔案。', '需要檔案、Xero 連線、Invoices／Attachments scopes 及權限。', 'xero'],
          ['Sync', '為尚未同步的現有 FCOS 收據建立 Xero 草稿供應商帳單及附件。', '成功同步後或 Xero／授權範圍不可用時停用。', 'xero'],
          ['Draft bill 連結', '在新瀏覽器分頁開啟已建立的 Xero 草稿供應商帳單。', '成功同步後顯示。', 'navigation'],
        ],
      },
      {
        id: 'automation',
        title: '5. Auto-Created Contacts 審計',
        purpose: '覆核已簽署的 Salesforce 事件；該事件要求 FCOS 為 Xero 缺少的聯絡人建立紀錄。此處只供審計，不會手動觸發建立聯絡人。',
        steps: [
          '覆核 Pending、Created、Already exists 及 Failed 總數。',
          '檢查準確 Salesforce Account、Xero Contact、配對依據及原因。',
          '如需調查或控制覆核，下載審計證據。',
        ],
        controls: [
          ['JSON audit', '以 JSON 下載最新完整自動建立聯絡人批次。', '存在 automation run 時啟用。', 'read'],
          ['CSV audit', '以 CSV 下載最新自動建立聯絡人項目。', '存在 automation run 時啟用。', 'read'],
        ],
      },
      {
        id: 'statuses',
        title: '6. 狀態、安全措施及疑難排解',
        purpose: '各列表顯示的首個封鎖原因就是下一步所需處理。身分、對應、scope、覆核、API 限額或財務證據不完整時，FCOS 會採取 fail-closed（拒絕繼續）原則。',
        steps: [
          'Eligible 代表按現有證據及權限可選取該項目。',
          'Protected legacy 代表 FCOS 找到不可自動重寫的歷史 Xero 會計紀錄。',
          'Blocked 或 Exception 代表必須處理顯示原因，或把它保留為受控例外。',
          '按鈕停用時，依次檢查連線、OAuth scopes、FCOS 權限、覆核確認、已選項目、對應完整性及外部操作閘門。',
          '出現 stale-write 或來源已更改錯誤時，先 Refresh 並重新建立 Preview；不要重複提交舊批次。',
          '失敗的 Xero 請求會保留 checkpoint。修正原因後應恢復受保護批次，而不是建立重複交易。',
        ],
        controls: [],
      },
    ],
  },
});

