export const XERO_PORTAL_MANUAL_LANGUAGES = Object.freeze([
  { id: 'en', label: 'English' },
  { id: 'zh-Hant', label: '繁體中文' },
]);

export const XERO_PORTAL_MANUALS = Object.freeze({
  en: {
    title: 'Xero Portal User Guide',
    subtitle: 'Choose what you want to do, follow the short steps, and open the detailed reference only when needed.',
    importantTitle: 'Three safety rules',
    important: [
      'Preview is safe: a read-only preview never changes Xero.',
      'Only a control marked “Xero write” changes Xero, and it still requires permission and review.',
      'Petroleum Product mappings follow the approved company rule; Finance reviews other mappings, documents and payments.',
    ],
    effectLabels: {
      read: 'Read only',
      fcos: 'FCOS save',
      xero: 'Xero write',
      navigation: 'Navigation',
    },
    taskTitle: 'What do you want to do?',
    taskHint: 'Choose a task. Its guide opens only when you need it.',
    tasks: [
      ['contacts', 'Clean up Xero contacts', 'Find unmatched contacts, review safe renames or archives, and apply only selected changes.'],
      ['accounting', 'Reconcile Salesforce with Xero', 'Run one complete check from 1 January 2026, resolve exceptions, then apply only Finance-reviewed actions.'],
      ['receipts', 'Process a receipt', 'Upload or scan a receipt, review its fields, save it, and optionally create a Xero draft bill.'],
      ['automation', 'Check what FCOS created', 'Review the automatic-contact audit without starting a new Xero action.'],
    ],
    workflowTitle: 'Safe order for accounting sync',
    workflow: [
      ['1', 'Check connection', 'Confirm the organisation, scopes, Salesforce source, and write-gate badges before starting.'],
      ['2', 'Check everything', 'Run the combined document and payment check, then open advanced setup only for mappings requested by an exception.'],
      ['3', 'Review and sync', 'Fix the exceptions you can resolve, select ready documents, and confirm the exact changes once.'],
      ['4', 'Verify settlement', 'Apply reviewed exact payments when their invoices are authorised. FCOS rechecks both populations; Waiting explains dependencies.'],
    ],
    sections: [
      {
        id: 'connection',
        title: '1. Check the connection',
        purpose: 'Confirm the Xero organisation, permissions, Salesforce source, and write gate before starting.',
        steps: [
          'Check the Connected badge and Xero tenant organisation before doing any review.',
          'Check Xero scopes. Contacts, invoices, attachments, payments, and accounting settings are enabled separately.',
          'Treat “Xero writes gated” as a safety lock: previews remain available, but guarded financial or contact writes cannot run.',
        ],
        controls: [
          ['User manual', 'Opens this bilingual manual. Use the language selector at the top to switch languages.', 'Always available inside Xero Portal.', 'navigation'],
          ['Refresh', 'Reloads connection status, receipts, the latest contact lifecycle run, and the latest automatic-contact run.', 'Disabled while another page-level action is running.', 'read'],
          ['Connect Xero', 'Starts Xero OAuth and returns to FCOS after the organisation is authorised.', 'Shown when disconnected and enabled only when the Xero app is configured.', 'fcos'],
          ['Reconnect scopes', 'Runs OAuth again without first deleting the stored connection, so missing accounting or payment scopes can be granted.', 'Shown only when connected but required financial scopes are missing.', 'fcos'],
          ['Disconnect', 'Removes the stored FCOS connection to the Xero tenant. It does not delete Xero contacts or transactions.', 'Shown when connected.', 'fcos'],
          ['Contacts / Accounting Sync / Receipts / Auto-Created Contacts / User Manual', 'Switches workspace sections without performing a data write.', 'Always available; individual actions inside a tab can still be permission-gated.', 'navigation'],
        ],
      },
      {
        id: 'contacts',
        title: '2. Clean up contacts',
        purpose: 'Compare Xero contacts with Salesforce. FCOS suggests changes, but nothing is applied until you review and select it.',
        steps: [
          'Choose the usage refresh depth. Use the cached/default scan normally; use incremental or full refresh only when current usage evidence is required.',
          'Click Preview. Review KPI totals, usage coverage, status explanations, estimated Xero calls, and every proposed row.',
          'Use search and filters to narrow the table. Only Eligible Rename or Archive rows can be selected.',
          'Select approved rows, tick Reviewed, and click Apply selected.',
          'Download JSON or CSV audit evidence when a review record is required.',
        ],
        controls: [
          ['Show unmatched Xero', 'Shows active Xero contacts that do not have a confirmed Salesforce Account match. Click again as Show all rows to remove the filter.', 'Available after the page loads.', 'navigation'],
          ['Preview', 'Reads Xero contacts and Salesforce Accounts, evaluates name/CL Key matches and usage, and prepares proposed actions. It does not rename or archive anything.', 'Requires a Xero connection and Contacts scope.', 'read'],
          ['Full usage refresh', 'Re-reads every supported Xero usage source before classifying unused contacts. It is slower and consumes more Xero calls.', 'Select before Preview. Selecting it disables Incremental usage refresh.', 'read'],
          ['Incremental usage refresh', 'Refreshes only usage evidence that can be updated incrementally, reducing calls compared with a full scan.', 'Select before Preview; unavailable while Full usage refresh is selected.', 'read'],
          ['JSON audit', 'Downloads the complete lifecycle run, including summary and row evidence, as JSON.', 'Enabled after a Preview exists.', 'read'],
          ['CSV audit', 'Downloads lifecycle rows as a spreadsheet-friendly CSV file.', 'Enabled after a Preview exists.', 'read'],
          ['Search Xero, Salesforce, CL Key', 'Filters the loaded rows by visible Xero and Salesforce identities, CL Key, Account ID, or reason.', 'Available after a Preview; does not rerun the scan.', 'navigation'],
          ['Action / Status / Reason filters', 'Filters the loaded result by proposed action, workflow status, or classification reason.', 'Available after a Preview.', 'navigation'],
          ['Row Use checkbox', 'Selects one eligible Rename or Archive row for the pending batch. Blocked, Keep, or Exception rows cannot be selected.', 'Enabled only for eligible rows.', 'navigation'],
          ['Select visible eligible', 'Selects all eligible rows currently included by the active filters. Existing selections outside the visible filter are replaced.', 'Enabled when at least one visible row is eligible.', 'navigation'],
          ['Clear', 'Clears all selected contact rows.', 'Always available.', 'navigation'],
          ['Reviewed', 'Confirms that the selected rows and evidence have been reviewed. It is a required acknowledgement, not an action by itself.', 'Tick after review and before Apply selected.', 'navigation'],
          ['Apply selected', 'Renames or archives the selected Xero contacts, then verifies and records the result.', 'Requires a Preview, Reviewed confirmation, at least one visible eligible selection, permission, and the contact-write gate.', 'xero'],
        ],
      },
      {
        id: 'accounting',
        title: '3. Sync accounting records',
        purpose: 'Prove that every in-scope Salesforce invoice, bill, credit note, and exact payment allocation is correctly represented in Xero.',
        steps: [
          'Click Check everything. The scope is fixed to accounting dates from 1 January 2026 and also includes records created since then with a missing accounting date; both documents and payments must finish before FCOS shows a percentage.',
          'The last completed check opens automatically. Start with Needs attention, then use Ready, Waiting and Matched to focus the work. Returning to the page checks for changes; Check everything always runs a full check.',
          'Each full check auto-approves Salesforce Petroleum_Product mappings: buyer 41100 Trading Sales, supplier 51100 Trading Purchase, tax NONE. Other product types keep their existing mappings. These approvals are audited in FCOS; Xero transactions still require review.',
          'Use Review / resolve on an exception to inspect every blocker and approve missing Product account/tax mappings in place. Mapping saves recheck the same document before invoice approval.',
          'Saving a mapping refreshes the results automatically and keeps unaffected selections. Exact existing documents and payments are linked in FCOS without a Xero write.',
          'Select ready documents and choose Review and sync selected. Inspect the exact changes and confirm once; FCOS retains the authorisation record internally.',
          'FCOS runs the confirmed selection and rechecks documents and payments. Use Resume approved sync after an interruption; changed records require review again.',
          'Review pending exact allocations, tick Finance reviewed payments, then apply only eligible payments. FCOS automatically rechecks again.',
        ],
        controls: [
          ['Fixed scope', 'Shows the non-editable Salesforce document and payment start date. Records created after it with a missing accounting date are included as exceptions.', 'Always 1 January 2026 for this reconciliation.', 'navigation'],
          ['Mappings', 'Reloads saved Product and bank mappings plus current Xero Chart of Accounts options.', 'Available while no accounting action is running.', 'read'],
          ['Check everything', 'Reads Salesforce and Xero, classifies documents and exact payments, calculates control totals, and derives mapping suggestions. No Xero transaction is changed.', 'Requires Xero connection plus Contacts, Invoices, Payments read, and Accounting settings scopes. Saves the check and exact links in FCOS.', 'fcos'],
          ['Product mapping Previous / Next', 'Moves through pages of Buyer and Supplier Product mapping rows. Suggestions and conflicts are shown first.', 'Available when the preview has loaded Products.', 'navigation'],
          ['Xero account selector', 'Chooses the Xero revenue or cost account for one exact Salesforce Product and direction.', 'Finance must confirm the accounting treatment.', 'navigation'],
          ['Tax type selector', 'Chooses the Xero tax treatment for that Product/direction. NONE is the default but must still be reviewed.', 'Finance must confirm the tax treatment.', 'navigation'],
          ['Approve mapping', 'Saves the selected Product/direction account and tax mapping in FCOS. It does not create or modify a Xero invoice.', 'Requires a selected Xero account and mapping permission.', 'fcos'],
          ['Update approval', 'Replaces an existing approved Product mapping with the newly selected account/tax treatment.', 'Shown for an already saved mapping; rerun the preview afterward.', 'fcos'],
          ['DBS / UBS bank Save icon', 'Maps the Salesforce bank name to one Xero bank account for exact payment allocation.', 'Requires a selected Xero bank account.', 'fcos'],
          ['Select eligible', 'Selects all currently eligible accounting documents in the loaded preview.', 'Available after a Preview.', 'navigation'],
          ['Clear', 'Clears all selected accounting documents.', 'Available after a Preview.', 'navigation'],
          ['Review and sync selected', 'Opens a review of selected documents, identities, dates, currencies, totals and exact changes.', 'Select ready documents. The financial sync gate must be enabled.', 'navigation'],
          ['Review / resolve', 'Opens one exception with its evidence, blockers and mapping controls. Rechecking keeps the same document open; unresolved identity or accounting conflicts cannot be overridden.', 'Available on Needs attention records. Ready records also offer a direct review.', 'navigation'],
          ['Approve and update', 'Approves and updates only the displayed eligible document, regardless of other selected rows. Current evidence and permissions are checked again.', 'Requires no blockers, a reviewable run and the financial write gate.', 'xero'],
          ['Approve and create draft', 'Approves creation of one displayed eligible draft, after resolving its required mappings.', 'Requires a new eligible document, a reviewable run and the financial write gate.', 'xero'],
          ['Approve link only', 'Records the reviewed link and retained differences in FCOS. Protected Xero accounting history remains unchanged.', 'Requires eligible matching evidence and Finance review.', 'fcos'],
          ['Confirm and sync', 'Records approval and runs the selected document changes. Records that changed after review remain for renewed review; unaffected records continue.', 'Review the exact document selection and financial effects first.', 'xero'],
          ['Resume approved sync', 'Continues an interrupted authorised run, retaining completed records and revalidating pending records.', 'Available for an authorised or partially completed run.', 'xero'],
          ['Document Previous / Next', 'Moves through pages of classified Salesforce documents without changing the selection.', 'Available after a Preview.', 'navigation'],
          ['Xero document link', 'Opens the matched Xero invoice, bill, or credit note in a new tab.', 'Shown when a Xero match exists.', 'navigation'],
          ['Preview payments', 'Classifies Salesforce Receivable and Payable payments against authorised Xero documents and saved bank mappings. It performs no payment write.', 'Use only after document processing and bank mapping are complete.', 'read'],
          ['Payment Use checkbox', 'Selects one exact eligible payment allocation.', 'Enabled only for exact payment_apply rows.', 'navigation'],
          ['Finance reviewed payments', 'Confirms Finance reviewed the selected payment dates, amounts, currencies, banks, and invoice allocations.', 'Required before Apply exact payments.', 'navigation'],
          ['Apply exact payments', 'Creates only the selected exact Xero payment allocations. Ambiguous remittances, deposits, bank charges, write-offs, and unsupported cases stay blocked.', 'Requires selections, review confirmation, bank mappings, authorised documents, permission, and the financial write gate.', 'xero'],
          ['Payment Previous / Next', 'Moves through pages of payment classifications.', 'Available after Preview payments.', 'navigation'],
        ],
      },
      {
        id: 'receipts',
        title: '4. Process receipts',
        purpose: 'Upload a receipt, check its fields, save it in FCOS, and optionally create a Xero draft bill.',
        steps: [
          'Choose an image or PDF up to the permitted file-size limit.',
          'For an image, run OCR and then verify every extracted field. Enter PDF details manually.',
          'Confirm Merchant, Date, Total, Currency, Account, Tax, Category, and Notes.',
          'Use Save draft to retain the receipt in FCOS, or Create Xero draft bill to save and immediately sync it.',
          'Use Sync in Receipt Audit for a previously saved receipt. Open Draft bill to inspect the Xero result.',
        ],
        controls: [
          ['Choose file', 'Selects an image or PDF receipt. The file is not uploaded until Save draft or Create Xero draft bill is clicked.', 'Required for saving or syncing.', 'navigation'],
          ['OCR image', 'Runs browser-based English OCR on an image and fills the editable receipt fields and OCR notes. Always verify the result.', 'Enabled for a selected file; PDFs require manual entry.', 'read'],
          ['Reset', 'Clears the editable receipt fields. It does not delete a previously saved receipt.', 'Always available.', 'navigation'],
          ['Save draft', 'Stores the receipt file and reviewed fields in FCOS without creating a Xero transaction.', 'Requires a selected file and receipt-management permission.', 'fcos'],
          ['Create Xero draft bill', 'Stores the receipt, creates an ACCPAY draft bill in Xero, and attaches the original file.', 'Requires a file, Xero connection, Invoices and Attachments scopes, and permission.', 'xero'],
          ['Sync', 'Creates and attaches the Xero draft bill for an existing FCOS receipt that has not yet synced.', 'Disabled after successful sync or when Xero/scopes are unavailable.', 'xero'],
          ['Draft bill link', 'Opens the created Xero draft bill in a new browser tab.', 'Shown after successful sync.', 'navigation'],
        ],
      },
      {
        id: 'automation',
        title: '5. Check automatic contact creation',
        purpose: 'Review what FCOS created automatically. This is a history view and starts no new Xero action.',
        steps: [
          'Review Pending, Created, Already exists, and Failed totals.',
          'Inspect the exact Salesforce Account, Xero Contact, match basis, and reason.',
          'Download audit evidence when required for investigation or control review.',
        ],
        controls: [
          ['JSON audit', 'Downloads the complete latest automatic-contact run as JSON.', 'Enabled when an automation run exists.', 'read'],
          ['CSV audit', 'Downloads the latest automatic-contact rows as CSV.', 'Enabled when an automation run exists.', 'read'],
        ],
      },
      {
        id: 'statuses',
        title: '6. Resolve blocked items',
        purpose: 'Read the first blocking reason for the next action. FCOS stops safely when required evidence is incomplete.',
        steps: [
          'Eligible means the row can be selected under the current evidence and permissions.',
          'Protected legacy means FCOS found historical Xero accounting that must not be rewritten automatically.',
          'Blocked or Exception means the displayed reason must be resolved or retained as a controlled exception.',
          'If a control is disabled, check connection, OAuth scopes, your FCOS capability, review acknowledgement, selected rows, mapping completeness, and the external-action gate.',
          'After a stale-write or changed-source error, Refresh and rebuild the Preview; do not repeatedly submit the old batch.',
          'A failed Xero request remains checkpointed. Correct the reason and resume the guarded run rather than creating a new duplicate transaction.',
        ],
        controls: [],
      },
    ],
  },
  'zh-Hant': {
    title: 'Xero Portal 操作指引',
    subtitle: '先選擇你要完成的工作，跟隨簡短步驟；只有需要時才展開詳細參考。',
    importantTitle: '三項安全原則',
    important: [
      '預覽是安全的：「唯讀預覽」絕不會更改 Xero。',
      '只有標示「寫入 Xero」的控制項會更改 Xero，而且仍須通過權限及覆核。',
      '石油產品對應按已核准的公司規則處理；其他對應、文件及付款由財務部覆核。',
    ],
    effectLabels: {
      read: '唯讀',
      fcos: '儲存至 FCOS',
      xero: '寫入 Xero',
      navigation: '導覽／篩選',
    },
    taskTitle: '你想完成甚麼？',
    taskHint: '選擇一項工作；只會展開你需要的指引。',
    tasks: [
      ['contacts', '整理 Xero 聯絡人', '找出未配對聯絡人，覆核安全的重新命名或封存建議，並只套用所選更改。'],
      ['accounting', '核對 Salesforce 與 Xero', '一次檢查由 2026 年 1 月 1 日起的全部資料、處理例外，然後只套用財務部已覆核操作。'],
      ['receipts', '處理收據', '上載或掃描收據、覆核資料、儲存，並可建立 Xero 草稿供應商帳單。'],
      ['automation', '檢查 FCOS 自動建立紀錄', '查看自動建立聯絡人的審計紀錄，而不會啟動新的 Xero 操作。'],
    ],
    workflowTitle: '會計同步的安全次序',
    workflow: [
      ['1', '檢查連線', '開始前確認機構、授權範圍、Salesforce 來源及寫入閘門標籤。'],
      ['2', '檢查全部', '一次檢查文件及付款；只有例外要求時才開啟進階設定核准產品及銀行對應。'],
      ['3', '檢閱並同步', '修正例外、選取可同步文件，檢閱準確變更後確認一次。'],
      ['4', '驗證結算', '發票獲授權後，套用已覆核的精確付款。等待中會顯示前置要求；全部核對一致才會顯示 100%。'],
    ],
    sections: [
      {
        id: 'connection',
        title: '1. 檢查連線',
        purpose: '開始前確認 Xero 機構、權限、Salesforce 來源及寫入閘門。',
        steps: [
          '進行任何覆核前，先檢查「已連接」標籤及 Xero 機構名稱。',
          '檢查 Xero 授權範圍；聯絡人、發票、附件、付款及會計設定會分開授權。',
          '「Xero 寫入閘門已鎖定」代表仍可預覽，但不可執行受保護的財務或聯絡人寫入。',
        ],
        controls: [
          ['使用手冊', '開啟本雙語手冊。可用頁頂的語言選擇器切換語言。', '在 Xero Portal 內隨時可用。', 'navigation'],
          ['重新整理', '重新載入連線狀態、收據、最新聯絡人生命週期批次及最新自動建立聯絡人批次。', '其他頁面操作進行時會停用。', 'read'],
          ['連接 Xero', '開始 Xero OAuth 授權，完成機構授權後返回 FCOS。', '未連線時顯示；只在 Xero 應用程式已設定時啟用。', 'fcos'],
          ['重新授權', '無須先刪除現有連線便可再次進行 OAuth，以補充會計或付款授權範圍。', '已連線但缺少所需財務範圍時才顯示。', 'fcos'],
          ['中斷連線', '移除 FCOS 儲存的 Xero tenant 連線；不會刪除 Xero 聯絡人或交易。', '已連線時顯示。', 'fcos'],
          ['聯絡人／會計同步／收據／自動建立聯絡人／使用手冊', '切換工作區，不會寫入資料。每個分頁內的操作仍可能受權限限制。', '一直可用。', 'navigation'],
        ],
      },
      {
        id: 'contacts',
        title: '2. 整理聯絡人',
        purpose: '把 Xero 聯絡人與 Salesforce 比對。FCOS 只會提出建議，覆核並選取後才會套用。',
        steps: [
          '選擇使用紀錄更新程度。一般使用快取／預設掃描；只有需要最新使用證據時才使用增量或完整更新。',
          '按「預覽」，覆核摘要、使用範圍、狀態說明、預計 Xero API 次數及每一建議項目。',
          '用搜尋及篩選收窄結果。只有合資格的「重新命名」或「封存」項目可選取。',
          '選取已核准項目，勾選「已覆核」，再按「套用所選項目」。',
          '如需保留覆核紀錄，可下載 JSON 或 CSV 審計檔案。',
        ],
        controls: [
          ['只顯示未配對 Xero', '只顯示沒有已確認 Salesforce Account 配對的現行 Xero 聯絡人。再次按下「顯示所有項目」可取消篩選。', '頁面載入後可用。', 'navigation'],
          ['預覽', '讀取 Xero 聯絡人及 Salesforce Accounts，評估名稱／CL Key 配對與使用情況，並準備建議操作；不會重新命名或封存任何資料。', '需要 Xero 連線及 Contacts scope。', 'read'],
          ['完整更新使用紀錄', '分類未使用聯絡人前，重新讀取所有受支援的 Xero 使用來源；所需時間及 API 次數較多。', '預覽前選取；選取後會停用「增量更新使用紀錄」。', 'read'],
          ['增量更新使用紀錄', '只更新可增量讀取的使用證據，比完整掃描耗用較少 API 次數。', '預覽前選取；「完整更新使用紀錄」開啟時不可用。', 'read'],
          ['JSON 審計檔', '以 JSON 下載完整生命週期批次，包括摘要及每行證據。', '有預覽後啟用。', 'read'],
          ['CSV 審計檔', '以適合試算表的 CSV 下載生命週期項目。', '有預覽後啟用。', 'read'],
          ['搜尋 Xero、Salesforce、CL Key', '按 Xero／Salesforce 身分、CL Key、Account ID 或原因篩選已載入的項目。', '有預覽後可用；不會重新掃描。', 'navigation'],
          ['操作／狀態／原因篩選', '按建議操作、工作狀態或分類原因篩選結果。', '有預覽後可用。', 'navigation'],
          ['每行「使用」勾選框', '把一個合資格的重新命名或封存項目加入待處理批次；已封鎖、保留或例外項目不可選取。', '只在合資格項目啟用。', 'navigation'],
          ['選取畫面中合資格項目', '選取目前篩選結果內所有合資格項目；會取代篩選結果以外的既有選取。', '至少有一個可見合資格項目時啟用。', 'navigation'],
          ['清除', '清除所有已選聯絡人項目。', '一直可用。', 'navigation'],
          ['已覆核', '確認已覆核所選項目及證據。此勾選本身不會執行更改。', '覆核完成後、「套用所選項目」前勾選。', 'navigation'],
          ['套用所選項目', '重新命名或封存所選 Xero 聯絡人，然後驗證並記錄結果。', '需要預覽、已覆核、至少一個可見合資格項目、相關權限及聯絡人寫入閘門。', 'xero'],
        ],
      },
      {
        id: 'accounting',
        title: '3. 同步會計紀錄',
        purpose: '證明範圍內每張 Salesforce 發票、帳單、貸項通知單及精確付款分配均正確反映於 Xero。',
        steps: [
          '按「檢查全部」。範圍固定為會計日期由 2026 年 1 月 1 日起的紀錄，亦包括此後建立但欠缺會計日期的紀錄；文件及付款均完成前不會顯示百分比。',
          '系統自動載入上次完成的核對。先查看「需要處理」，再使用「可同步」、「等待中」及「已核對」分類。',
          '每次完整核對自動核准 Salesforce Petroleum_Product 對應：買方 41100 Trading Sales、供應商 51100 Trading Purchase、稅務 NONE。其他產品類型保留原有對應；核准會記錄於 FCOS，Xero 交易仍需覆核。',
          '在例外項目按「檢閱／解決」，查看所有阻礙並核准缺少的產品會計科目／稅務對應。儲存後會重新核對同一文件，再供審批。',
          '儲存對應後自動更新，並保留未受影響的選取。已存在的準確文件及付款會在 FCOS 建立連結，不會寫入 Xero 交易。',
          '選取可同步文件，按「檢閱並同步所選項目」。確認文件、貨幣及金額後按「確認並同步」；審批紀錄仍會保留。',
          '完成後自動核對文件及付款。中斷時使用「繼續已核准的同步」；變更項目需要重新檢閱。',
          '覆核待處理精確付款分配，勾選「財務部已覆核付款」，然後只套用合資格付款；完成後 FCOS 會再次自動檢查。',
        ],
        controls: [
          ['固定範圍', '顯示不可編輯的 Salesforce 文件及付款開始日期；此後建立但欠缺會計日期的紀錄會列為例外。', '此對帳永遠由 2026 年 1 月 1 日開始。', 'navigation'],
          ['對應設定', '重新載入已儲存的產品／銀行對應及目前 Xero Chart of Accounts 選項。', '沒有其他會計操作進行時可用。', 'read'],
          ['檢查全部', '讀取 Salesforce 及 Xero、分類文件及精確付款、計算控制總額及產生對應建議；不會更改任何 Xero 交易。', '需要 Xero 連線及 Contacts、Invoices、Payments read、Accounting settings scopes；會在 FCOS 儲存核對及準確連結。', 'fcos'],
          ['產品對應「上一頁／下一頁」', '瀏覽買方及供應商產品對應頁面；建議及衝突會優先顯示。', '預覽載入產品後可用。', 'navigation'],
          ['Xero 帳戶選擇', '為一個準確 Salesforce Product 及方向選擇 Xero 收入或成本科目。', '必須由財務部確認會計處理。', 'navigation'],
          ['稅務類別選擇', '選擇該產品／方向的 Xero 稅項處理。預設為 NONE，但仍須覆核。', '必須由財務部確認稅務處理。', 'navigation'],
          ['核准對應', '把所選產品／方向的會計科目及稅項對應儲存至 FCOS；不會建立或更改 Xero 發票。', '需要選定 Xero 科目及對應設定權限。', 'fcos'],
          ['更新核准', '以新選擇的科目／稅項取代已核准的產品對應。', '已有對應時顯示；儲存後須重新預覽。', 'fcos'],
          ['DBS／UBS 銀行「儲存」圖示', '把 Salesforce 銀行名稱對應至一個 Xero 銀行帳戶，以供精確付款分配。', '需要選定 Xero 銀行帳戶。', 'fcos'],
          ['選取合資格項目', '選取已載入預覽內所有合資格會計文件。', '有預覽後可用。', 'navigation'],
          ['清除', '清除所有已選會計文件。', '有預覽後可用。', 'navigation'],
          ['檢閱並同步所選項目', '檢閱所選文件、身分、日期、貨幣、總額及實際差異。', '選取可同步文件；財務同步必須已啟用。', 'navigation'],
          ['檢閱／解決', '開啟單一例外的證據、阻礙及對應控制項。重新核對後保留同一文件；身分或會計衝突不能略過。', '需要處理的紀錄可用；合資格紀錄亦有直接檢閱按鈕。', 'navigation'],
          ['核准並更新', '只核准及更新目前顯示的合資格文件，不包括其他已選項目；執行前再次驗證證據及權限。', '沒有阻礙、批次可覆核及財務寫入已啟用時可用。', 'xero'],
          ['核准並建立草稿', '對應問題解決後，只為目前顯示的合資格文件建立草稿。', '新文件合資格、批次可覆核及財務寫入已啟用時可用。', 'xero'],
          ['只核准連結', '在 FCOS 記錄已覆核連結及保留差異；受保護的 Xero 會計歷史不會改變。', '配對證據合資格並經財務覆核後可用。', 'fcos'],
          ['確認並同步', '記錄審批並同步所選變更。已變更項目須再次檢閱，其餘項目可繼續。', '先檢閱所選文件及財務影響。', 'xero'],
          ['繼續已核准的同步', '繼續已中斷的授權批次；保留已完成記錄並重新核對待處理記錄。', '適用於已授權或部分完成的批次。', 'xero'],
          ['文件「上一頁／下一頁」', '瀏覽已分類 Salesforce 文件頁面，不會改變選取。', '有預覽後可用。', 'navigation'],
          ['Xero 文件連結', '在新分頁開啟已配對的 Xero invoice、bill 或 credit note。', '有 Xero 配對時顯示。', 'navigation'],
          ['預覽付款', '按已授權 Xero 文件及銀行對應分類 Salesforce Receivable／Payable payments；不會寫入付款。', '只應在完成文件處理及銀行對應後使用。', 'read'],
          ['付款「使用」勾選框', '選取一項精確而合資格的付款分配。', '只在精確 payment_apply 項目啟用。', 'navigation'],
          ['財務部已覆核付款', '確認財務部已覆核所選付款日期、金額、貨幣、銀行及發票分配。', '「套用精確付款」前必須勾選。', 'navigation'],
          ['套用精確付款', '只建立所選精確 Xero 付款分配；含糊匯款、按金、銀行費用、撇帳及不支援項目仍會被封鎖。', '需要選取、覆核確認、銀行對應、已授權文件、權限及財務寫入閘門。', 'xero'],
          ['付款「上一頁／下一頁」', '瀏覽付款分類頁面。', '預覽付款後可用。', 'navigation'],
        ],
      },
      {
        id: 'receipts',
        title: '4. 處理收據',
        purpose: '上載收據、檢查欄位、儲存至 FCOS，並可選擇建立 Xero 草稿供應商帳單。',
        steps: [
          '選擇符合檔案大小限制的圖片或 PDF。',
          '圖片可使用 OCR，之後必須核對每個擷取欄位；PDF 資料須手動輸入。',
          '確認商戶、日期、總額、貨幣、帳戶、稅務類別、分類及備註。',
          '使用「儲存草稿」只儲存於 FCOS；或使用「建立 Xero 草稿供應商帳單」儲存並即時同步。',
          '已儲存但未同步的收據可在「收據審計」使用「同步」；使用「草稿供應商帳單」連結檢查結果。',
        ],
        controls: [
          ['選擇檔案', '選擇圖片或 PDF 收據。按「儲存草稿」或「建立 Xero 草稿供應商帳單」前不會上載。', '儲存或同步前必須選擇。', 'navigation'],
          ['OCR 圖片', '在瀏覽器執行英文圖片 OCR，填入可編輯收據欄位及 OCR 備註；必須人手覆核。', '選擇檔案後啟用；PDF 須手動輸入。', 'read'],
          ['重設', '清除可編輯收據欄位；不會刪除已儲存收據。', '一直可用。', 'navigation'],
          ['儲存草稿', '把收據檔案及已覆核欄位儲存至 FCOS，不建立 Xero 交易。', '需要已選檔案及收據管理權限。', 'fcos'],
          ['建立 Xero 草稿供應商帳單', '儲存收據、在 Xero 建立 ACCPAY 草稿供應商帳單，並附上原始檔案。', '需要檔案、Xero 連線、Invoices／Attachments scopes 及權限。', 'xero'],
          ['同步', '為尚未同步的現有 FCOS 收據建立 Xero 草稿供應商帳單及附件。', '成功同步後或 Xero／授權範圍不可用時停用。', 'xero'],
          ['草稿供應商帳單連結', '在新瀏覽器分頁開啟已建立的 Xero 草稿供應商帳單。', '成功同步後顯示。', 'navigation'],
        ],
      },
      {
        id: 'automation',
        title: '5. 檢查自動建立聯絡人',
        purpose: '查看 FCOS 自動建立的紀錄。此處只顯示歷史，不會啟動新的 Xero 操作。',
        steps: [
          '覆核待處理、已建立、已存在及失敗總數。',
          '檢查準確 Salesforce Account、Xero 聯絡人、配對依據及原因。',
          '如需調查或控制覆核，下載審計證據。',
        ],
        controls: [
          ['JSON 審計檔', '以 JSON 下載最新完整自動建立聯絡人批次。', '存在 automation run 時啟用。', 'read'],
          ['CSV 審計檔', '以 CSV 下載最新自動建立聯絡人項目。', '存在 automation run 時啟用。', 'read'],
        ],
      },
      {
        id: 'statuses',
        title: '6. 處理被封鎖項目',
        purpose: '先閱讀首個封鎖原因，這就是下一步。所需證據不完整時，FCOS 會安全停止。',
        steps: [
          '「合資格」代表按現有證據及權限可選取該項目。',
          '「受保護舊紀錄」代表 FCOS 找到不可自動重寫的歷史 Xero 會計紀錄。',
          '「已封鎖」或「例外」代表必須處理顯示原因，或把它保留為受控例外。',
          '按鈕停用時，依次檢查連線、OAuth 授權範圍、FCOS 權限、覆核確認、已選項目、對應完整性及外部操作閘門。',
          '出現過時寫入或來源已更改錯誤時，先「重新整理」並重新建立預覽；不要重複提交舊批次。',
          '失敗的 Xero 請求會保留檢查點。修正原因後應恢復受保護批次，而不是建立重複交易。',
        ],
        controls: [],
      },
    ],
  },
});
