export const XERO_PORTAL_LANGUAGE_STORAGE_KEY = 'fcos:xero-portal-language:v1';

export const XERO_PORTAL_UI_LANGUAGES = Object.freeze([
  { id: 'en', label: 'English' },
  { id: 'zh-Hant', label: '繁體中文' },
]);

const EN = {
  locale: 'en-GB',
  languageLabel: 'Xero Portal language',
  common: {
    available: 'Available', missing: 'Missing', unavailable: 'Not available', unknown: 'Unknown', notConfigured: 'Not configured',
    readWrite: 'Read / write', readOnly: 'Read only', pending: 'Pending', previous: 'Previous', next: 'Next', clear: 'Clear',
    use: 'Use', action: 'Action', status: 'Status', reason: 'Reason', date: 'Date', total: 'Total', type: 'Type', amount: 'Amount', bank: 'Bank',
    open: 'Open', exact: 'Exact', notSet: 'Not set', noClKey: 'No CL Key', noStem: 'No STEM', noType: 'No type', noIssue: 'No issue', none: 'None',
  },
  header: {
    title: 'Xero Portal', connected: 'Connected', disconnected: 'Disconnected', writesEnabled: 'Xero writes enabled', writesGated: 'Xero writes gated',
    subtitle: 'Finance-reviewed Salesforce accounting sync, receipt draft bills, Account contact sync, unused-contact review, and automation audit.',
    manual: 'User manual', refresh: 'Refresh', reconnect: 'Reconnect scopes', disconnect: 'Disconnect', connect: 'Connect Xero',
    loadingTitle: 'Loading Xero Portal', loadingDescription: 'FCOS is reading the Xero connection, receipt audit, and latest contact lifecycle run.',
  },
  tabs: { contacts: 'Contacts', accounting: 'Accounting Sync', receipts: 'Receipts', automation: 'Auto-Created Contacts', manual: 'User Manual' },
  toasts: {
    connected: 'Xero connected', connectedDescription: 'FCOS can now read and update the connected Xero organisation.',
    connectionFailed: 'Xero connection failed', connectionFailedDescription: 'Check the Xero app settings and try again.', connectionUnavailable: 'Xero connection unavailable',
    disconnectFailed: 'Disconnect failed', disconnected: 'Xero disconnected', previewFailed: 'Preview failed', applyFailed: 'Apply failed',
    changesApplied: 'Xero contact changes applied', ocrImagesOnly: 'OCR supports image receipts', ocrImagesOnlyDescription: 'PDF receipts can still be saved and synced after entering the fields manually.',
    ocrFailed: 'OCR failed', ocrFailedDescription: 'Enter the receipt fields manually.', fileRequired: 'Receipt file required', fileRequiredDescription: 'Choose an image or PDF receipt first.',
    receiptSyncFailed: 'Receipt sync failed', receiptSaveFailed: 'Receipt save failed', receiptSent: 'Receipt sent to Xero', receiptSaved: 'Receipt saved',
    receiptSentDescription: 'A draft bill was created and the file attached.', receiptSavedDescription: 'The receipt is stored in FCOS.',
  },
  panels: {
    tenant: 'Xero tenant', organisation: 'Organisation', notConnected: 'Not connected', tenantId: 'Tenant ID', tokenExpires: 'Token expires', redirectUri: 'Redirect URI',
    scopes: 'Xero scopes', contacts: 'Contacts', invoices: 'Invoices', attachments: 'Attachments', payments: 'Payments', accountingSettings: 'Accounting settings',
    salesforce: 'Salesforce source', auth: 'Auth', instance: 'Instance', clKey: 'CL Key', hkOnly: 'HK* only', deliveryFrom: 'Delivery from',
    automation: 'Latest automation', run: 'Run', event: 'Event', created: 'Created', skippedFailed: 'Skipped / failed', noRun: 'No run',
  },
  contacts: {
    kpis: { active: 'Non-archived Xero', archived: 'Archived Xero', unmatched: 'Unmatched active', rename: 'Rename eligible', archive: 'Archive eligible', exceptions: 'Exceptions' },
    title: 'Contact Cleanup & Sync', description: 'Matching uses Xero current name only: Salesforce Account name or the Salesforce CL Key after removing leading HK. ContactNumber and AccountNumber are reference fields only.',
    showAll: 'Show all rows', showUnmatched: 'Show unmatched Xero', preview: 'Preview', fullUsage: 'Full usage refresh', incrementalUsage: 'Incremental usage refresh',
    jsonAudit: 'JSON audit', csvAudit: 'CSV audit', callEstimate: 'Xero call estimate', verify: 'Verify', apply: 'Apply',
    noRun: 'No contact lifecycle preview has been generated in FCOS yet. The KPI cards and table will populate after Preview.',
    lastRun: (id, date, count) => `Last contact lifecycle run ${id} loaded ${date} with ${count} audit rows.`,
    search: 'Search Xero, Salesforce, CL Key', allActions: 'All actions', allStatuses: 'All statuses', allReasons: 'All reasons',
    showing: (shown, selected, eligible) => `Showing ${shown} rows. Selected ${selected} total, ${eligible} visible eligible.`,
    selectVisible: 'Select visible eligible', reviewed: 'Reviewed', applySelected: 'Apply selected', tableLabel: 'Xero contact lifecycle rows',
    xeroContact: 'Xero contact', salesforceSource: 'Salesforce source', match: 'Match', usage: 'Usage',
    noXeroMatch: 'No Xero match', noContactNumber: 'No contact no.', noAccountNumber: 'No account no.', noStatus: 'No status', noSalesforceMatch: 'No Salesforce match',
    noRowsTitle: 'No matching rows', noRowsDescription: 'Adjust filters or run a new preview.', noPreviewTitle: 'No lifecycle preview', noPreviewDescription: 'Run Preview to load Xero contacts, Salesforce matches, and archive exceptions.',
    noReadableUsage: 'No readable usage', previewRequired: 'Preview required',
  },
  receipts: {
    title: 'Scan Receipt', file: 'Receipt file', chooseFile: 'Choose file', noFile: 'No file selected', ocr: 'OCR image', reset: 'Reset', merchant: 'Merchant',
    date: 'Date', total: 'Total', currency: 'Currency', account: 'Account', tax: 'Tax', category: 'Category', notes: 'Notes / OCR text', save: 'Save draft', createBill: 'Create Xero draft bill',
    auditTitle: 'Receipt Audit', auditLabel: 'Receipt audit', receipt: 'Receipt', status: 'Status', xero: 'Xero', updated: 'Updated', action: 'Action', draftBill: 'Draft bill', notSynced: 'Not synced', sync: 'Sync',
    emptyTitle: 'No receipts stored', emptyDescription: 'Upload a receipt to create the first draft audit row.',
  },
  automation: {
    title: 'Salesforce Trigger Contact Creation', description: 'FCOS records every signed Salesforce event that checks for newly used Account names missing from Xero.',
    pending: 'Pending', created: 'Created', alreadyExists: 'Already exists', failed: 'Failed', tableLabel: 'Auto-created Xero contact rows',
    salesforceAccount: 'Salesforce Account', xeroContact: 'Xero Contact', match: 'Match', reason: 'Reason', noAccount: 'No Account', noXeroContact: 'No Xero contact',
    emptyTitle: 'No automation audit run yet', emptyDescription: 'A Salesforce trigger run will appear here after a signed event reaches FCOS.',
  },
  manual: { loadingTitle: 'Loading Xero Portal manual', loadingDescription: 'FCOS is loading the English and Traditional Chinese user guide.' },
  actions: { archive: 'Archive', rename: 'Rename', exception: 'Exception', keep: 'Keep', unknown: 'Unknown' },
  statuses: {
    eligible: 'Eligible', blocked: 'Blocked', kept: 'Kept', updated: 'Updated', archived: 'Archived', failed: 'Failed', complete: 'Complete', missing: 'Missing', pending: 'Pending', created: 'Created', skipped: 'Skipped',
    'already-exists': 'Already exists', 'not-selected': 'Not selected', protected: 'Protected', authorised: 'Authorised', partial: 'Partial', 'ready_for_review': 'Ready for review', synced: 'Synced', unknown: 'Unknown',
  },
  statusDescriptions: {
    eligible: 'Safe to apply after review and selection.', blocked: 'Cannot be applied automatically; review the reason and map or correct the data first.',
    kept: 'No Xero mutation is needed; the contact remains active.', 'not-selected': 'The row was eligible in preview but was not selected in the apply step.',
    updated: 'The selected Xero contact rename was applied.', archived: 'The selected Xero contact was archived in Xero.', failed: 'The row was selected but Xero or validation rejected the mutation.',
  },
  reasons: {
    'blank-salesforce-key': 'Missing Salesforce CL Key', 'blank-salesforce-name': 'Missing Salesforce Account name', 'xero-name-too-long': 'Salesforce name is longer than Xero allows',
    'duplicate-salesforce-key': 'Duplicate Salesforce CL Key', 'duplicate-xero-name': 'Duplicate Xero contact name', 'ambiguous-xero-name-match': 'Salesforce name and HK-stripped CL Key matched different Xero contacts',
    'missing-xero-contact': 'No Xero contact matched the Salesforce name or HK-stripped CL Key name', 'archived-only-match': 'Only archived Xero contacts matched', 'unchanged-name': 'Xero contact already has this name',
    'duplicate-target-name': 'Multiple Salesforce rows propose the same Xero name', 'target-name-collision': 'Another active Xero contact already uses this name', 'invalid-account-id': 'Salesforce Account ID is missing or invalid',
    'unsupported-source-field': 'Salesforce source object or Account field is not enabled for auto-create', 'salesforce-account-not-found': 'Salesforce Account was not found',
    'inactive-salesforce-account': 'Salesforce Account is inactive or suspended', 'unsupported-salesforce-record-type': 'Salesforce Account record type is not enabled for Xero contacts',
    'non-hk-cl-key': 'Salesforce CL Key does not start with HK', 'duplicate-create-name': 'Multiple missing Salesforce Accounts would create the same Xero contact name',
    'xero-contact-exists': 'Matching active Xero contact already exists', 'xero-contact-created': 'Created in Xero', 'xero-create-failed': 'Xero contact create failed',
    'xero-not-connected': 'Xero is not connected with accounting.contacts', 'unused-unmatched-xero-contact': 'Unused Xero contact has no Salesforce match',
    'used-unmatched-xero-contact': 'Used Xero contact has no Salesforce match', 'nonzero-balance': 'Xero contact has a nonzero balance',
    'ambiguous-salesforce-match': 'Xero contact is protected by an ambiguous Salesforce match', 'already-archived': 'Xero contact is already archived',
    'blocked-scope': 'Xero scope cannot read this usage source', 'usage-scan-incomplete': 'Readable Xero usage scan is incomplete', 'stale-preview': 'Xero contact changed after preview',
    'not-selected': 'Eligible row was not selected for apply',
  },
  matchFields: { SalesforceName: 'Salesforce name', ClKeyWithoutHk: 'CL key without HK', SalesforceNameAndClKeyWithoutHk: 'Salesforce name + CL key without HK' },
  usageSources: { invoices: 'Invoices, bills, and credit notes', 'bank-transactions': 'Bank transactions', payments: 'Payments', overpayments: 'Overpayments', prepayments: 'Prepayments', 'expense-claims': 'Expense claims', receipts: 'Receipts' },
  recordTypes: { Buyer: 'Buyer', Supplier: 'Supplier', Buyer_Supplier: 'Buyer & Supplier', Broker: 'Broker' },
  financial: {
    loadingTitle: 'Loading accounting controls', loadingDescription: 'FCOS is loading service-only mappings and the connected Xero Chart of Accounts.',
    title: '2026 accounting cutover', manualOnly: 'Manual only', gateEnabled: 'Financial write gate enabled', gateLocked: 'Financial write gate locked',
    description: 'Preview classifies every Salesforce buyer invoice, supplier bill and credit note dated from the cutoff. Xero writes require a reviewed selection and a separately enabled production gate.',
    cutoff: 'Accounting cutoff', mappings: 'Mappings', preview: 'Build read-only preview', reconnect: 'Reconnect Xero once to grant accounting.settings.read and the write-capable accounting.payments scope.',
    mappingTitle: 'Finance-approved Product mappings', mappingDescription: 'Default tax is NONE. Buyer sales and supplier costs are mapped independently. Legacy suggestions are never approved automatically.',
    savedMappings: (count) => `${count} saved mappings`, proposalSummary: (proposed, conflicts) => `${proposed} evidence-backed suggestions · ${conflicts} conflicts`,
    mappingRange: (from, to, total) => `Mappings ${from}–${to} of ${total} · suggestions first`, productMappingsLabel: 'Xero product mappings',
    direction: 'Direction', salesforceProduct: 'Salesforce Product', xeroAccount: 'Xero account', taxType: 'Tax type', action: 'Action',
    noProducts: 'Build the first preview to load every Product used by 2026 financial documents.', bankTitle: 'Payment bank mappings',
    bankDescription: 'Exact Salesforce Receivable/Payable payments remain blocked until Finance maps each source bank to one Xero bank account.',
    classified: 'Classified', eligible: 'Eligible', createDrafts: 'Create drafts', safeUpdates: 'Safe updates', protectedLegacy: 'Protected legacy', blocked: 'Blocked',
    reviewTitle: 'Finance batch review', runSummary: (id, status, selected, eligible) => `Run ${id} · ${status} · ${selected} selected of ${eligible} eligible.`,
    selectEligible: 'Select eligible', financeReviewed: 'Finance reviewed', authorise: 'Authorise batch', runSelected: 'Run selected',
    rowRange: (from, to, total) => `Rows ${from}–${to} of ${total}`, documentTableLabel: 'Xero financial cutover classifications', salesforceDocument: 'Salesforce document', accountStem: 'Account / STEM',
    due: 'Due', noActiveMatch: 'No active match', differenceCount: (count) => `${count} Salesforce difference(s)`,
    paymentsTitle: 'Exact payment allocations', paymentsDescription: 'Available only after the matching Xero invoice or bill is authorised. Remittances, deposits, charges, write-offs and ambiguous allocations remain exceptions.',
    previewPayments: 'Preview payments', paymentSummary: (total, eligible) => `${total} classified · ${eligible} exact allocations eligible.`, financeReviewedPayments: 'Finance reviewed payments', applyPayments: 'Apply exact payments',
    paymentTableLabel: 'Exact Xero payment classifications', payment: 'Payment', actionReason: 'Action / reason', noPaymentPreview: 'No payment preview loaded.',
    noPreviewTitle: 'No accounting preview yet', noPreviewDescription: 'Approve Product mappings as they are discovered, then rerun until every 2026 document is classified exactly once.',
    selectAccount: 'Select Xero account', selectBank: 'Select Xero bank account', approveMapping: 'Approve mapping', updateApproval: 'Update approval',
    mappingSaveFailed: 'Mapping save failed', mappingSaved: 'Product mapping saved', bankSaveFailed: 'Bank mapping save failed', bankSaved: (bank) => `${bank} bank mapping saved`,
    approved: 'Approved', approvedBy: (email) => `Approved by ${email}`, suggested: (count, basis) => `Suggested from ${count} exact matched legacy document${count === 1 ? '' : 's'} · ${basis}`,
    conflicting: (items) => `Conflicting legacy evidence: ${items}`, noSuggestion: 'No exact legacy suggestion',
    basis: { exact_line: 'line coding matched', uniform_document: 'uniform document coding', default: 'consistent line/document coding' },
    directions: { buyer: 'Buyer', supplier: 'Supplier' },
    authorisationFailed: 'Authorisation failed', batchAuthorised: 'Batch authorised', batchAuthorisedDescription: (count) => `${count} accounting records are checkpointed for the guarded Xero run.`,
    batchStopped: 'Xero batch stopped safely', batchCompleted: 'Xero document batch completed', paymentPreviewFailed: 'Payment preview failed', paymentStopped: 'Payment apply stopped safely', paymentsApplied: 'Exact Xero payments applied',
    outcome: (summary) => `${summary.created || 0} created, ${summary.updated || 0} updated, ${summary.linked || 0} linked, ${summary.applied || 0} payments, ${summary.failed || 0} failed.`,
    documentKinds: { buyer_invoice: 'Buyer invoice', supplier_bill: 'Supplier bill', buyer_credit_note: 'Buyer credit note', supplier_credit_note: 'Supplier credit note' },
    actions: { create_draft: 'Create draft', safe_update: 'Safe update', protected_legacy: 'Protected legacy', link_exact: 'Link exact match', blocked: 'Blocked', payment_apply: 'Apply payment' },
  },
};

const ZH_HANT = {
  ...EN,
  locale: 'zh-HK',
  languageLabel: 'Xero Portal 語言',
  common: {
    available: '可用', missing: '缺少', unavailable: '沒有資料', unknown: '未知', notConfigured: '未設定', readWrite: '讀取／寫入', readOnly: '唯讀', pending: '待處理',
    previous: '上一頁', next: '下一頁', clear: '清除', use: '使用', action: '操作', status: '狀態', reason: '原因', date: '日期', total: '總額', type: '類別', amount: '金額', bank: '銀行',
    open: '開啟', exact: '完全相符', notSet: '未設定', noClKey: '沒有 CL Key', noStem: '沒有 STEM', noType: '沒有類別', noIssue: '沒有問題', none: '無',
  },
  header: {
    title: 'Xero Portal', connected: '已連線', disconnected: '未連線', writesEnabled: 'Xero 寫入已啟用', writesGated: 'Xero 寫入已鎖定',
    subtitle: '經財務部覆核的 Salesforce 會計同步、收據草稿供應商帳單、Account 聯絡人同步、未使用聯絡人覆核及自動化審計。',
    manual: '使用手冊', refresh: '重新整理', reconnect: '重新授權', disconnect: '中斷連線', connect: '連接 Xero',
    loadingTitle: '正在載入 Xero Portal', loadingDescription: 'FCOS 正在讀取 Xero 連線、收據審計及最新聯絡人生命週期批次。',
  },
  tabs: { contacts: '聯絡人', accounting: '會計同步', receipts: '收據', automation: '自動建立聯絡人', manual: '使用手冊' },
  toasts: {
    connected: 'Xero 已連線', connectedDescription: 'FCOS 現可讀取及更新已連接的 Xero 機構。', connectionFailed: 'Xero 連線失敗', connectionFailedDescription: '請檢查 Xero 應用程式設定後再試。',
    connectionUnavailable: 'Xero 連線暫不可用', disconnectFailed: '中斷連線失敗', disconnected: 'Xero 已中斷連線', previewFailed: '預覽失敗', applyFailed: '套用失敗',
    changesApplied: '已套用 Xero 聯絡人更改', ocrImagesOnly: 'OCR 只支援圖片收據', ocrImagesOnlyDescription: 'PDF 收據仍可在手動輸入資料後儲存及同步。',
    ocrFailed: 'OCR 失敗', ocrFailedDescription: '請手動輸入收據資料。', fileRequired: '必須提供收據檔案', fileRequiredDescription: '請先選擇圖片或 PDF 收據。',
    receiptSyncFailed: '收據同步失敗', receiptSaveFailed: '收據儲存失敗', receiptSent: '收據已傳送至 Xero', receiptSaved: '收據已儲存',
    receiptSentDescription: '已建立草稿供應商帳單並附上原始檔案。', receiptSavedDescription: '收據已儲存於 FCOS。',
  },
  panels: {
    tenant: 'Xero 機構', organisation: '機構', notConnected: '未連線', tenantId: 'Tenant ID', tokenExpires: '權杖到期時間', redirectUri: '重新導向 URI',
    scopes: 'Xero 授權範圍', contacts: '聯絡人', invoices: '發票及帳單', attachments: '附件', payments: '付款', accountingSettings: '會計設定',
    salesforce: 'Salesforce 來源', auth: '驗證方式', instance: '執行個體', clKey: 'CL Key', hkOnly: '只限 HK*', deliveryFrom: '交付日期起點',
    automation: '最新自動化', run: '批次', event: '事件', created: '已建立', skippedFailed: '略過／失敗', noRun: '沒有批次',
  },
  contacts: {
    kpis: { active: '未封存 Xero', archived: '已封存 Xero', unmatched: '未配對有效聯絡人', rename: '可重新命名', archive: '可封存', exceptions: '例外' },
    title: '聯絡人整理及同步', description: '配對只使用 Xero 現有名稱：Salesforce Account 名稱，或移除開首 HK 後的 Salesforce CL Key。ContactNumber 及 AccountNumber 只供參考。',
    showAll: '顯示所有項目', showUnmatched: '只顯示未配對 Xero', preview: '預覽', fullUsage: '完整更新使用紀錄', incrementalUsage: '增量更新使用紀錄',
    jsonAudit: 'JSON 審計檔', csvAudit: 'CSV 審計檔', callEstimate: 'Xero API 呼叫估算', verify: '驗證', apply: '套用',
    noRun: 'FCOS 尚未建立聯絡人生命週期預覽。按「預覽」後會顯示 KPI 及表格。',
    lastRun: (id, date, count) => `最近聯絡人生命週期批次 ${id} 於 ${date} 載入，共有 ${count} 行審計紀錄。`,
    search: '搜尋 Xero、Salesforce、CL Key', allActions: '所有操作', allStatuses: '所有狀態', allReasons: '所有原因',
    showing: (shown, selected, eligible) => `顯示 ${shown} 行；已選取 ${selected} 行，其中畫面內有 ${eligible} 行合資格。`,
    selectVisible: '選取畫面中合資格項目', reviewed: '已覆核', applySelected: '套用所選項目', tableLabel: 'Xero 聯絡人生命週期項目',
    xeroContact: 'Xero 聯絡人', salesforceSource: 'Salesforce 來源', match: '配對方式', usage: '使用紀錄',
    noXeroMatch: '沒有 Xero 配對', noContactNumber: '沒有聯絡人編號', noAccountNumber: '沒有帳戶編號', noStatus: '沒有狀態', noSalesforceMatch: '沒有 Salesforce 配對',
    noRowsTitle: '沒有符合項目', noRowsDescription: '請調整篩選條件或重新預覽。', noPreviewTitle: '尚未建立生命週期預覽', noPreviewDescription: '按「預覽」載入 Xero 聯絡人、Salesforce 配對及封存例外。',
    noReadableUsage: '沒有可讀取的使用紀錄', previewRequired: '需要先預覽',
  },
  receipts: {
    title: '掃描收據', file: '收據檔案', chooseFile: '選擇檔案', noFile: '尚未選擇檔案', ocr: 'OCR 圖片', reset: '重設', merchant: '商戶', date: '日期', total: '總額',
    currency: '貨幣', account: '會計科目', tax: '稅務類別', category: '分類', notes: '備註／OCR 文字', save: '儲存草稿', createBill: '建立 Xero 草稿供應商帳單',
    auditTitle: '收據審計', auditLabel: '收據審計', receipt: '收據', status: '狀態', xero: 'Xero', updated: '更新時間', action: '操作', draftBill: '草稿供應商帳單', notSynced: '未同步', sync: '同步',
    emptyTitle: '沒有已儲存收據', emptyDescription: '上載收據以建立第一行草稿審計紀錄。',
  },
  automation: {
    title: 'Salesforce 觸發建立聯絡人', description: 'FCOS 會記錄每個已簽署的 Salesforce 事件，以檢查新使用的 Account 名稱是否尚未存在於 Xero。',
    pending: '待處理', created: '已建立', alreadyExists: '已存在', failed: '失敗', tableLabel: '自動建立的 Xero 聯絡人項目',
    salesforceAccount: 'Salesforce Account', xeroContact: 'Xero 聯絡人', match: '配對方式', reason: '原因', noAccount: '沒有 Account', noXeroContact: '沒有 Xero 聯絡人',
    emptyTitle: '尚未有自動化審計批次', emptyDescription: '當已簽署的 Salesforce 事件到達 FCOS 後，批次會顯示於此。',
  },
  manual: { loadingTitle: '正在載入 Xero Portal 使用手冊', loadingDescription: 'FCOS 正在載入英文及繁體中文使用指引。' },
  actions: { archive: '封存', rename: '重新命名', exception: '例外', keep: '保留', unknown: '未知' },
  statuses: {
    eligible: '合資格', blocked: '已封鎖', kept: '已保留', updated: '已更新', archived: '已封存', failed: '失敗', complete: '完成', missing: '缺少', pending: '待處理', created: '已建立', skipped: '已略過',
    'already-exists': '已存在', 'not-selected': '未選取', protected: '受保護', authorised: '已授權', partial: '部分完成', 'ready_for_review': '可供覆核', synced: '已同步', unknown: '未知',
  },
  statusDescriptions: {
    eligible: '覆核及選取後可安全套用。', blocked: '不可自動套用；請覆核原因並先完成對應或修正資料。', kept: '不需要更改 Xero；聯絡人維持有效。',
    'not-selected': '此行在預覽中合資格，但套用時未有選取。', updated: '已套用所選 Xero 聯絡人重新命名。', archived: '已在 Xero 封存所選聯絡人。', failed: '已選取此行，但 Xero 或驗證拒絕更改。',
  },
  reasons: {
    'blank-salesforce-key': '缺少 Salesforce CL Key', 'blank-salesforce-name': '缺少 Salesforce Account 名稱', 'xero-name-too-long': 'Salesforce 名稱超出 Xero 長度限制',
    'duplicate-salesforce-key': 'Salesforce CL Key 重複', 'duplicate-xero-name': 'Xero 聯絡人名稱重複', 'ambiguous-xero-name-match': 'Salesforce 名稱及移除 HK 的 CL Key 分別配對至不同 Xero 聯絡人',
    'missing-xero-contact': 'Salesforce 名稱或移除 HK 的 CL Key 名稱均未配對到 Xero 聯絡人', 'archived-only-match': '只配對到已封存的 Xero 聯絡人', 'unchanged-name': 'Xero 聯絡人已使用此名稱',
    'duplicate-target-name': '多個 Salesforce 項目建議使用相同 Xero 名稱', 'target-name-collision': '另一個有效 Xero 聯絡人已使用此名稱', 'invalid-account-id': 'Salesforce Account ID 缺少或無效',
    'unsupported-source-field': 'Salesforce 來源物件或 Account 欄位未啟用自動建立', 'salesforce-account-not-found': '找不到 Salesforce Account',
    'inactive-salesforce-account': 'Salesforce Account 已停用或暫停', 'unsupported-salesforce-record-type': '此 Salesforce Account Record Type 未啟用 Xero 聯絡人',
    'non-hk-cl-key': 'Salesforce CL Key 並非以 HK 開始', 'duplicate-create-name': '多個缺少的 Salesforce Account 會建立相同 Xero 聯絡人名稱',
    'xero-contact-exists': '相符的有效 Xero 聯絡人已存在', 'xero-contact-created': '已在 Xero 建立', 'xero-create-failed': '建立 Xero 聯絡人失敗',
    'xero-not-connected': 'Xero 未連接 accounting.contacts', 'unused-unmatched-xero-contact': '未使用的 Xero 聯絡人沒有 Salesforce 配對',
    'used-unmatched-xero-contact': '已使用的 Xero 聯絡人沒有 Salesforce 配對', 'nonzero-balance': 'Xero 聯絡人仍有非零結餘',
    'ambiguous-salesforce-match': '此 Xero 聯絡人因 Salesforce 配對不明確而受保護', 'already-archived': 'Xero 聯絡人已封存',
    'blocked-scope': 'Xero 授權範圍無法讀取此使用來源', 'usage-scan-incomplete': '可讀取的 Xero 使用掃描並不完整', 'stale-preview': 'Xero 聯絡人在預覽後已變更',
    'not-selected': '套用時未有選取此合資格項目',
  },
  matchFields: { SalesforceName: 'Salesforce 名稱', ClKeyWithoutHk: '移除 HK 的 CL Key', SalesforceNameAndClKeyWithoutHk: 'Salesforce 名稱及移除 HK 的 CL Key' },
  usageSources: { invoices: '發票、帳單及貸項通知單', 'bank-transactions': '銀行交易', payments: '付款', overpayments: '多付金額', prepayments: '預付款', 'expense-claims': '費用申報', receipts: '收據' },
  recordTypes: { Buyer: '買方', Supplier: '供應商', Buyer_Supplier: '買方及供應商', Broker: '經紀' },
  financial: {
    loadingTitle: '正在載入會計控制項', loadingDescription: 'FCOS 正在載入只供服務使用的對應設定及已連接的 Xero Chart of Accounts。',
    title: '2026 年會計切換', manualOnly: '只限手動', gateEnabled: '財務寫入閘門已啟用', gateLocked: '財務寫入閘門已鎖定',
    description: '預覽會分類由截數日起的每張 Salesforce 買方發票、供應商帳單及貸項通知單。寫入 Xero 前必須覆核所選項目，並另行啟用生產寫入閘門。',
    cutoff: '會計截數日期', mappings: '對應設定', preview: '建立唯讀預覽', reconnect: '請重新授權 Xero，以授予 accounting.settings.read 及可寫入的 accounting.payments 授權範圍。',
    mappingTitle: '財務部核准的產品對應', mappingDescription: '預設稅務類別為 NONE。買方銷售及供應商成本會分開對應；系統不會自動核准舊系統建議。',
    savedMappings: (count) => `已儲存 ${count} 個對應`, proposalSummary: (proposed, conflicts) => `${proposed} 個有證據的建議 · ${conflicts} 個衝突`,
    mappingRange: (from, to, total) => `對應 ${from}–${to}／共 ${total} 個 · 建議優先`, productMappingsLabel: 'Xero 產品對應',
    direction: '方向', salesforceProduct: 'Salesforce 產品', xeroAccount: 'Xero 帳戶', taxType: '稅務類別', action: '操作',
    noProducts: '建立首次預覽，以載入 2026 年財務文件使用的所有產品。', bankTitle: '付款銀行對應',
    bankDescription: '在財務部把每個 Salesforce 收款／付款銀行對應至一個 Xero 銀行帳戶前，精確付款仍會被封鎖。',
    classified: '已分類', eligible: '合資格', createDrafts: '建立草稿', safeUpdates: '安全更新', protectedLegacy: '受保護舊紀錄', blocked: '已封鎖',
    reviewTitle: '財務批次覆核', runSummary: (id, status, selected, eligible) => `批次 ${id} · ${status} · 已選 ${selected}／${eligible} 個合資格項目。`,
    selectEligible: '選取合資格項目', financeReviewed: '財務部已覆核', authorise: '授權批次', runSelected: '執行所選項目',
    rowRange: (from, to, total) => `第 ${from}–${to} 行／共 ${total} 行`, documentTableLabel: 'Xero 財務切換分類', salesforceDocument: 'Salesforce 文件', accountStem: 'Account／STEM',
    due: '到期日', noActiveMatch: '沒有有效配對', differenceCount: (count) => `${count} 項 Salesforce 差異`,
    paymentsTitle: '精確付款分配', paymentsDescription: '只在相符的 Xero 發票或帳單獲授權後可用。匯款、按金、費用、撇帳及不明確分配仍列為例外。',
    previewPayments: '預覽付款', paymentSummary: (total, eligible) => `已分類 ${total} 項 · ${eligible} 項精確付款合資格。`, financeReviewedPayments: '財務部已覆核付款', applyPayments: '套用精確付款',
    paymentTableLabel: '精確 Xero 付款分類', payment: '付款', actionReason: '操作／原因', noPaymentPreview: '尚未載入付款預覽。',
    noPreviewTitle: '尚未建立會計預覽', noPreviewDescription: '產品出現後逐一核准對應，再重新預覽，直至每份 2026 年文件只被分類一次。',
    selectAccount: '選擇 Xero 帳戶', selectBank: '選擇 Xero 銀行帳戶', approveMapping: '核准對應', updateApproval: '更新核准',
    mappingSaveFailed: '儲存對應失敗', mappingSaved: '產品對應已儲存', bankSaveFailed: '儲存銀行對應失敗', bankSaved: (bank) => `${bank} 銀行對應已儲存`,
    approved: '已核准', approvedBy: (email) => `由 ${email} 核准`, suggested: (count, basis) => `根據 ${count} 份完全配對的舊系統文件建議 · ${basis}`,
    conflicting: (items) => `舊系統證據有衝突：${items}`, noSuggestion: '沒有完全配對的舊系統建議',
    basis: { exact_line: '明細編碼相符', uniform_document: '整份文件使用同一編碼', default: '明細／文件編碼一致' },
    directions: { buyer: '買方', supplier: '供應商' },
    authorisationFailed: '授權失敗', batchAuthorised: '批次已授權', batchAuthorisedDescription: (count) => `${count} 項會計紀錄已建立檢查點，等候受保護的 Xero 執行。`,
    batchStopped: 'Xero 批次已安全停止', batchCompleted: 'Xero 文件批次已完成', paymentPreviewFailed: '付款預覽失敗', paymentStopped: '套用付款已安全停止', paymentsApplied: '已套用精確 Xero 付款',
    outcome: (summary) => `建立 ${summary.created || 0} 項、更新 ${summary.updated || 0} 項、連結 ${summary.linked || 0} 項、付款 ${summary.applied || 0} 項、失敗 ${summary.failed || 0} 項。`,
    documentKinds: { buyer_invoice: '買方發票', supplier_bill: '供應商帳單', buyer_credit_note: '買方貸項通知單', supplier_credit_note: '供應商貸項通知單' },
    actions: { create_draft: '建立草稿', safe_update: '安全更新', protected_legacy: '受保護舊紀錄', link_exact: '連結完全相符項目', blocked: '已封鎖', payment_apply: '套用付款' },
  },
};

export const XERO_PORTAL_UI_COPY = Object.freeze({ en: EN, 'zh-Hant': ZH_HANT });

export function normalizeXeroPortalLanguage(value) {
  return value === 'zh-Hant' ? 'zh-Hant' : 'en';
}

export function xeroPortalUiCopy(language) {
  return XERO_PORTAL_UI_COPY[normalizeXeroPortalLanguage(language)];
}
