export const XERO_PORTAL_LANGUAGE_STORAGE_KEY = 'fcos:xero-portal-language:v1';
export const XERO_PORTAL_UI_LANGUAGES = Object.freeze([{ id: 'en', label: 'English' }]);

const EN = {
  "locale": "en-GB",
  "languageLabel": "Xero Portal language",
  "common": {
    "available": "Available",
    "missing": "Missing",
    "unavailable": "Not available",
    "unknown": "Unknown",
    "notConfigured": "Not configured",
    "readWrite": "Read / write",
    "readOnly": "Read only",
    "pending": "Pending",
    "previous": "Previous",
    "next": "Next",
    "clear": "Clear",
    "use": "Use",
    "action": "Action",
    "status": "Status",
    "reason": "Reason",
    "date": "Date",
    "total": "Total",
    "type": "Type",
    "amount": "Amount",
    "bank": "Bank",
    "open": "Open",
    "exact": "Exact",
    "notSet": "Not set",
    "noClKey": "No CL Key",
    "noStem": "No STEM",
    "noType": "No type",
    "noIssue": "No issue",
    "none": "None"
  },
  "header": {
    "title": "Xero Portal",
    "connected": "Connected",
    "disconnected": "Disconnected",
    "writesEnabled": "Xero writes enabled",
    "writesGated": "Xero writes gated",
    "subtitle": "Finance-reviewed Salesforce accounting sync, receipt draft bills, Account contact sync, unused-contact review, and automation audit.",
    "manual": "User manual",
    "refresh": "Refresh",
    "reconnect": "Reconnect scopes",
    "disconnect": "Disconnect",
    "connect": "Connect Xero",
    "loadingTitle": "Loading Xero Portal",
    "loadingDescription": "FCOS is reading the Xero connection, receipt audit, and latest contact lifecycle run."
  },
  "tabs": {
    "contacts": "Contacts",
    "accounting": "Salesforce → Xero",
    "receipts": "Receipts",
    "automation": "Auto-Created Contacts",
    "manual": "User Manual"
  },
  "toasts": {
    "connected": "Xero connected",
    "connectedDescription": "FCOS can now read and update the connected Xero organisation.",
    "connectionFailed": "Xero connection failed",
    "connectionFailedDescription": "Check the Xero app settings and try again.",
    "connectionUnavailable": "Xero connection unavailable",
    "disconnectFailed": "Disconnect failed",
    "disconnected": "Xero disconnected",
    "previewFailed": "Preview failed",
    "applyFailed": "Apply failed",
    "changesApplied": "Xero contact changes applied",
    "ocrImagesOnly": "OCR supports image receipts",
    "ocrImagesOnlyDescription": "PDF receipts can still be saved and synced after entering the fields manually.",
    "ocrFailed": "OCR failed",
    "ocrFailedDescription": "Enter the receipt fields manually.",
    "fileRequired": "Receipt file required",
    "fileRequiredDescription": "Choose an image or PDF receipt first.",
    "receiptSyncFailed": "Receipt sync failed",
    "receiptSaveFailed": "Receipt save failed",
    "receiptSent": "Receipt sent to Xero",
    "receiptSaved": "Receipt saved",
    "receiptSentDescription": "A draft bill was created and the file attached.",
    "receiptSavedDescription": "The receipt is stored in FCOS."
  },
  "panels": {
    "tenant": "Xero tenant",
    "organisation": "Organisation",
    "notConnected": "Not connected",
    "tenantId": "Tenant ID",
    "tokenExpires": "Token expires",
    "redirectUri": "Redirect URI",
    "scopes": "Xero scopes",
    "contacts": "Contacts",
    "invoices": "Invoices",
    "attachments": "Attachments",
    "payments": "Payments",
    "accountingSettings": "Accounting settings",
    "salesforce": "Salesforce source",
    "auth": "Auth",
    "instance": "Instance",
    "clKey": "CL Key",
    "hkOnly": "HK* only",
    "deliveryFrom": "Delivery from",
    "automation": "Latest automation",
    "run": "Run",
    "event": "Event",
    "created": "Created",
    "skippedFailed": "Skipped / failed",
    "noRun": "No run"
  },
  "contacts": {
    "kpis": {
      "active": "Non-archived Xero",
      "archived": "Archived Xero",
      "unmatched": "Unmatched active",
      "rename": "Rename eligible",
      "archive": "Archive eligible",
      "exceptions": "Exceptions"
    },
    "title": "Contact Cleanup & Sync",
    "description": "Matching uses Xero current name only: Salesforce Account name or the Salesforce CL Key after removing leading HK. ContactNumber and AccountNumber are reference fields only.",
    "showAll": "Show all rows",
    "showUnmatched": "Show unmatched Xero",
    "preview": "Preview",
    "fullUsage": "Full usage refresh",
    "incrementalUsage": "Incremental usage refresh",
    "jsonAudit": "JSON audit",
    "csvAudit": "CSV audit",
    "callEstimate": "Xero call estimate",
    "verify": "Verify",
    "apply": "Apply",
    "noRun": "No contact lifecycle preview has been generated in FCOS yet. The KPI cards and table will populate after Preview.",
    "lastRun": (id, date, count) => `Last contact lifecycle run ${id} loaded ${date} with ${count} audit rows.`,
    "search": "Search Xero, Salesforce, CL Key",
    "allActions": "All actions",
    "allStatuses": "All statuses",
    "allReasons": "All reasons",
    "showing": (shown, selected, eligible) => `Showing ${shown} rows. Selected ${selected} total, ${eligible} visible eligible.`,
    "selectVisible": "Select visible eligible",
    "reviewed": "Reviewed",
    "applySelected": "Apply selected",
    "tableLabel": "Xero contact lifecycle rows",
    "xeroContact": "Xero contact",
    "salesforceSource": "Salesforce source",
    "match": "Match",
    "usage": "Usage",
    "noXeroMatch": "No Xero match",
    "noContactNumber": "No contact no.",
    "noAccountNumber": "No account no.",
    "noStatus": "No status",
    "noSalesforceMatch": "No Salesforce match",
    "noRowsTitle": "No matching rows",
    "noRowsDescription": "Adjust filters or run a new preview.",
    "noPreviewTitle": "No lifecycle preview",
    "noPreviewDescription": "Run Preview to load Xero contacts, Salesforce matches, and archive exceptions.",
    "noReadableUsage": "No readable usage",
    "previewRequired": "Preview required",
    "usageSourceTotal": (source, count) => `${source}: ${count}`,
    "yearUnavailable": (count) => `Year unavailable: ${count}`,
    "yearBreakdownPending": "Year breakdown not yet scanned. Refresh Preview.",
    "identity": {
      "review": "Review Xero-only identity",
      "title": "Contact identity decision",
      "description": "Verify this Xero contact only when evidence shows that no Salesforce Account is required. The decision is audited and rechecked against the current contact.",
      "current": "Current audited decision",
      "verified": "Verified Xero-only",
      "revoked": "Verification revoked",
      "none": "No decision recorded",
      "decision": "Decision",
      "verify": "Verify Xero-only",
      "revoke": "Revoke verification",
      "revision": "Revision",
      "actor": "Reviewed by",
      "updated": "Updated",
      "reference": "Evidence reference",
      "note": "Evidence note",
      "noteRequirement": "Explain the counterparty identity in at least 15 characters; include a source reference.",
      "reviewed": "I reviewed the current Xero contact and evidence",
      "cancel": "Cancel",
      "saveFailed": "The identity decision could not be saved.",
      "uncertain": "The decision result is uncertain. Do not retry; refresh the contact preview and inspect the audited decision."
    },
    "repair": {
      "selected": (count) => `${count} missing contacts selected separately`,
      "reviewed": "I reviewed these missing Salesforce contacts",
      "createSelected": "Create selected missing contacts",
      "limit": "Select no more than 25 contacts per reviewed batch.",
      "failed": "Contact repair failed",
      "completed": "Contact repair reviewed; the preview will refresh.",
      "uncertain": "Contact creation outcome uncertain — do not retry",
      "uncertainDetail": "The response did not confirm every selected contact. Refresh the contact preview and inspect Xero before another attempt.",
      "outcome": (summary) => `${summary.created || 0} created, ${summary.existing || 0} already existed, ${summary.blocked || 0} blocked, ${summary.uncertain || 0} uncertain. Resolve uncertain results in Xero before another attempt.`
    }
  },
  "receipts": {
    "title": "Scan Receipt",
    "file": "Receipt file",
    "chooseFile": "Choose file",
    "noFile": "No file selected",
    "ocr": "OCR image",
    "reset": "Reset",
    "merchant": "Merchant",
    "date": "Date",
    "total": "Total",
    "currency": "Currency",
    "account": "Account",
    "tax": "Tax",
    "category": "Category",
    "notes": "Notes / OCR text",
    "save": "Save draft",
    "createBill": "Create Xero draft bill",
    "auditTitle": "Receipt Audit",
    "auditLabel": "Receipt audit",
    "receipt": "Receipt",
    "status": "Status",
    "xero": "Xero",
    "updated": "Updated",
    "action": "Action",
    "draftBill": "Draft bill",
    "notSynced": "Not synced",
    "sync": "Sync",
    "emptyTitle": "No receipts stored",
    "emptyDescription": "Upload a receipt to create the first draft audit row."
  },
  "automation": {
    "title": "Salesforce Trigger Contact Creation",
    "description": "FCOS records every signed Salesforce event that checks for newly used Account names missing from Xero.",
    "pending": "Pending",
    "created": "Created",
    "alreadyExists": "Already exists",
    "failed": "Failed",
    "tableLabel": "Auto-created Xero contact rows",
    "salesforceAccount": "Salesforce Account",
    "xeroContact": "Xero Contact",
    "match": "Match",
    "reason": "Reason",
    "noAccount": "No Account",
    "noXeroContact": "No Xero contact",
    "emptyTitle": "No automation audit run yet",
    "emptyDescription": "A Salesforce trigger run will appear here after a signed event reaches FCOS."
  },
  "manual": {
    "loadingTitle": "Loading Xero Portal manual",
    "loadingDescription": "FCOS is loading the English user guide."
  },
  "actions": {
    "archive": "Archive",
    "rename": "Rename",
    "exception": "Exception",
    "keep": "Keep",
    "unknown": "Unknown"
  },
  "statuses": {
    "eligible": "Eligible",
    "blocked": "Blocked",
    "kept": "Kept",
    "updated": "Updated",
    "archived": "Archived",
    "failed": "Failed",
    "complete": "Complete",
    "missing": "Missing",
    "pending": "Pending",
    "created": "Created",
    "skipped": "Skipped",
    "already-exists": "Already exists",
    "not-selected": "Not selected",
    "protected": "Protected",
    "authorised": "Authorised",
    "partial": "Partial",
    "ready_for_review": "Ready for review",
    "synced": "Synced",
    "unknown": "Unknown"
  },
  "statusDescriptions": {
    "eligible": "Safe to apply after review and selection.",
    "blocked": "Cannot be applied automatically; review the reason and map or correct the data first.",
    "kept": "No Xero mutation is needed; the contact remains active.",
    "not-selected": "The row was eligible in preview but was not selected in the apply step.",
    "updated": "The selected Xero contact rename was applied.",
    "archived": "The selected Xero contact was archived in Xero.",
    "failed": "The row was selected but Xero or validation rejected the mutation."
  },
  "reasons": {
    "blank-salesforce-key": "Missing Salesforce CL Key",
    "blank-salesforce-name": "Missing Salesforce Account name",
    "xero-name-too-long": "Salesforce name is longer than Xero allows",
    "duplicate-salesforce-key": "Duplicate Salesforce CL Key",
    "duplicate-xero-name": "Duplicate Xero contact name",
    "ambiguous-xero-name-match": "Salesforce name and HK-stripped CL Key matched different Xero contacts",
    "missing-xero-contact": "No Xero contact matched the Salesforce name or HK-stripped CL Key name",
    "archived-only-match": "Only archived Xero contacts matched",
    "unchanged-name": "Xero contact already has this name",
    "duplicate-target-name": "Multiple Salesforce rows propose the same Xero name",
    "target-name-collision": "Another active Xero contact already uses this name",
    "invalid-account-id": "Salesforce Account ID is missing or invalid",
    "unsupported-source-field": "Salesforce source object or Account field is not enabled for auto-create",
    "salesforce-account-not-found": "Salesforce Account was not found",
    "inactive-salesforce-account": "Salesforce Account is inactive or suspended",
    "unsupported-salesforce-record-type": "Salesforce Account record type is not enabled for Xero contacts",
    "non-hk-cl-key": "Salesforce CL Key does not start with HK",
    "duplicate-create-name": "Multiple missing Salesforce Accounts would create the same Xero contact name",
    "xero-contact-exists": "Matching active Xero contact already exists",
    "xero-contact-created": "Created in Xero",
    "xero-create-failed": "Xero contact create failed",
    "xero-not-connected": "Xero is not connected with accounting.contacts",
    "unused-unmatched-xero-contact": "Unused Xero contact has no Salesforce match",
    "used-unmatched-xero-contact": "Used Xero contact has no Salesforce match",
    "nonzero-balance": "Xero contact has a nonzero balance",
    "ambiguous-salesforce-match": "Xero contact is protected by an ambiguous Salesforce match",
    "already-archived": "Xero contact is already archived",
    "blocked-scope": "Xero scope cannot read this usage source",
    "usage-scan-incomplete": "Readable Xero usage scan is incomplete",
    "stale-preview": "Xero contact changed after preview",
    "not-selected": "Eligible row was not selected for apply",
    "verified-xero-only": "Verified Xero-only counterparty; no Salesforce Account is required",
    "verification-stale": "Xero-only identity changed; verify it again"
  },
  "matchFields": {
    "SalesforceName": "Salesforce name",
    "ClKeyWithoutHk": "CL key without HK",
    "SalesforceNameAndClKeyWithoutHk": "Salesforce name + CL key without HK"
  },
  "usageSources": {
    "invoices": "Invoices and bills",
    "credit-notes": "Credit notes",
    "bank-transactions": "Bank transactions",
    "payments": "Payments",
    "overpayments": "Overpayments",
    "prepayments": "Prepayments",
    "expense-claims": "Expense claims",
    "receipts": "Receipts"
  },
  "recordTypes": {
    "Buyer": "Buyer",
    "Supplier": "Supplier",
    "Buyer_Supplier": "Buyer & Supplier",
    "Broker": "Broker"
  },
  "financial": {
    "loadingTitle": "Loading accounting controls",
    "loadingDescription": "Loading mappings and the Xero Chart of Accounts.",
    "gateEnabled": "Financial write gate enabled",
    "gateLocked": "Financial write gate locked",
    "mappings": "Mappings",
    "preview": "Build read-only preview",
    "reconnect": "Reconnect Xero once to grant accounting.settings.read and the write-capable accounting.payments scope.",
    "reconciliationTitle": "Salesforce → Xero reconciliation",
    "fixedScope": "Fixed scope: from 1 Jan 2026",
    "reconciliationDescription": "Compare scoped Salesforce invoices, bills, credits and payments with Xero. Missing dates or unsupported/incomplete payments remain exceptions.",
    "checkEverything": "Check everything",
    "checkingEverything": "Checking documents and payments…",
    "completion": "Verified completion",
    "salesforceRecords": "Salesforce records",
    "correctInXero": "Correct in Xero",
    "awaitingSync": "Awaiting sync",
    "exceptions": "Exceptions",
    "setupTitle": "Advanced mapping setup",
    "setupDescription": "Use when an exception needs a product, tax or bank mapping.",
    "reconciliationStatuses": {
      "not_checked": "Not checked",
      "incomplete_check": "Check incomplete",
      "attention_required": "Action required",
      "sync_required": "Ready for reviewed sync",
      "reconciled": "100% reconciled"
    },
    "reconciliationDescriptions": {
      "not_checked": "Run Check everything to compare Salesforce and Xero.",
      "incomplete_check": "Completion requires document and payment checks.",
      "attention_required": "Resolve exceptions; preserve Xero history and differences for Finance review.",
      "sync_required": "Review, approve and run pending actions. FCOS then rechecks Xero.",
      "reconciled": "All transactions match or have accepted legacy differences; no blockers remain. Retained differences stay visible."
    },
    "mappingTitle": "Finance-approved Product mappings",
    "mappingDescription": "Tax defaults to NONE; map buyer sales and supplier costs separately. Legacy suggestions require approval.",
    "savedMappings": (count) => `${count} saved mappings`,
    "proposalSummary": (proposed, conflicts) => `${proposed} evidence-backed suggestions · ${conflicts} conflicts`,
    "mappingRange": (from, to, total) => `Mappings ${from}–${to} of ${total} · suggestions first`,
    "productMappingsLabel": "Xero product mappings",
    "direction": "Direction",
    "salesforceProduct": "Salesforce Product",
    "xeroAccount": "Xero account",
    "taxType": "Tax type",
    "action": "Action",
    "noProducts": "Build the first preview to load every Product used by 2026 financial documents.",
    "bankTitle": "Payment bank mappings",
    "bankDescription": "Finance must map each Salesforce source bank to one Xero bank account before exact Receivable/Payable allocations.",
    "reviewTitle": "Finance batch review",
    "runSummary": (id, status, selected, eligible) => `Run ${id} · ${status} · ${selected} selected of ${eligible} eligible.`,
    "selectEligible": "Select eligible",
    "authorise": "Authorise batch",
    "rowRange": (from, to, total) => `Rows ${from}–${to} of ${total}`,
    "documentTableLabel": "Xero financial cutover classifications",
    "salesforceDocument": "Salesforce document",
    "accountStem": "Account / STEM",
    "due": "Due",
    "noActiveMatch": "No active match",
    "differenceCount": (count) => `${count} Salesforce difference(s)`,
    "paymentsTitle": "Exact payment allocations",
    "paymentsDescription": "Payments need a linked, authorised Xero invoice. Verified remittance headers are summaries; adjustments and unclear allocations need review.",
    "previewPayments": "Preview payments",
    "paymentSummary": (total, eligible) => `${total} classified · ${eligible} exact allocations eligible.`,
    "financeReviewedPayments": "Finance reviewed payments",
    "applyPayments": "Apply exact payments",
    "reviewPaymentReference": "Review retained reference",
    "paymentReferenceTitle": "Review retained Xero payment reference",
    "paymentReferenceDescription": "Salesforce has no payment reference. Verify invoice, bank, date, amount and currency, then link the existing Xero payment. Only the FCOS mapping changes.",
    "sourceReference": "Salesforce explicit reference",
    "sourceFallbackReference": "Salesforce payment name fallback",
    "retainedXeroReference": "Retained Xero reference",
    "xeroPaymentId": "Xero payment ID",
    "xeroInvoice": "Xero invoice or bill",
    "bankAccountId": "Xero bank account ID",
    "missingReference": "Absent",
    "paymentReferenceEvidenceMissing": "Payment evidence is incomplete or changed. Recheck everything before approval.",
    "paymentReferenceLinked": "Existing payment reference linked",
    "paymentReferenceStopped": "Payment reference link stopped safely",
    "paymentReferenceOutcomeMissing": "The server did not confirm a linked outcome. Recheck before retrying.",
    "approvePaymentReference": "Approve link only",
    "paymentTableLabel": "Exact Xero payment classifications",
    "fileDiscovery": {
      "title": "Attached PDF candidates",
      "description": "Only file details have been checked; invoice contents are unverified.",
      "captured": "Lookup captured (Hong Kong)",
      "stale": "Saved preview observation; attachments may have changed.",
      "complete": "Attached PDF found; issued-document verification pending.",
      "empty": "No directly attached PDF found in the complete lookup.",
      "partial": "Cannot verify issued document; attachment lookup is incomplete.",
      "unavailable": "Cannot verify issued document; attachment lookup is unavailable.",
      "not_checked": "Cannot verify issued document; attachments not checked.",
      "count": (count) => `${count} PDF candidate(s) observed`,
      "displayLimit": (shown, count) => `Showing ${shown} of ${count} observed candidates.`,
      "inspect": "Inspect STEM documents"
    },
    "paymentHoldsTitle": "Xero payment evidence requiring review",
    "paymentHoldsCount": (count) => `${count} Xero payment record${count === 1 ? '' : 's'} held for separate review`,
    "paymentHoldsDescription": "These records remain unresolved and cannot be selected for automatic linking or payment. Other verified invoice payments can still be reviewed.",
    "paymentHoldsDetails": "Show held payment records",
    "paymentHoldRefundReason": "Finance must verify the refund and its original credit, prepayment or overpayment before resolving it.",
    "paymentHoldInvalidReason": "The payment association is incomplete or conflicting. Finance must resolve its transaction identity.",
    "paymentHoldKinds": {
      "credit_note": "Credit-note refund",
      "prepayment": "Prepayment refund",
      "overpayment": "Overpayment refund",
      "invoice": "Invoice payment evidence",
      "unknown": "Unresolved payment evidence"
    },
    "payment": "Payment",
    "actionReason": "Action / reason",
    "noPaymentPreview": "No payment preview loaded.",
    "noPreviewTitle": "No accounting preview yet",
    "noPreviewDescription": "Approve Product mappings as they are discovered, then rerun until every 2026 document is classified exactly once.",
    "selectAccount": "Select Xero account",
    "selectBank": "Select Xero bank account",
    "approveMapping": "Approve mapping",
    "updateApproval": "Update approval",
    "mappingSaveFailed": "Mapping save failed",
    "mappingSaved": "Product mapping saved",
    "bankSaveFailed": "Bank mapping save failed",
    "bankSaved": (bank) => `${bank} bank mapping saved`,
    "approved": "Approved",
    "approvedBy": (email) => `Approved by ${email}`,
    "suggested": (count, basis) => `Suggested from ${count} exact matched legacy document${count === 1 ? '' : 's'} · ${basis}`,
    "conflicting": (items) => `Conflicting legacy evidence: ${items}`,
    "noSuggestion": "No exact legacy suggestion",
    "basis": {
      "exact_line": "line coding matched",
      "uniform_document": "uniform document coding",
      "default": "consistent line/document coding"
    },
    "directions": {
      "buyer": "Buyer",
      "supplier": "Supplier"
    },
    "batchCompleted": "Xero document batch completed",
    "paymentPreviewFailed": "Payment preview failed",
    "paymentStopped": "Payment apply stopped safely",
    "paymentsApplied": "Exact Xero payments applied",
    "outcome": (summary) => `${summary.created || 0} created, ${summary.updated || 0} updated, ${summary.linked || 0} linked, ${summary.applied || 0} payments, ${summary.failed || 0} failed.`,
    "documentKinds": {
      "buyer_invoice": "Buyer invoice",
      "supplier_bill": "Supplier bill",
      "buyer_credit_note": "Buyer credit note",
      "supplier_credit_note": "Supplier credit note"
    },
    "actions": {
      "create_draft": "Create draft",
      "safe_update": "Safe update",
      "protected_legacy": "Protected legacy",
      "link_exact": "Link exact match",
      "blocked": "Blocked",
      "payment_apply": "Apply payment",
      "payment_reference_link": "Retained reference · link only",
      "payment_link": "Linked payment"
    }
  }
};

export const XERO_PORTAL_UI_COPY = Object.freeze({ en: EN });

// Old saved language preferences and callers remain compatible with English-only UI.
export function normalizeXeroPortalLanguage(_value) { return 'en'; }
export function xeroPortalUiCopy(_language) { return EN; }
