import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('Nom B policies enforce roles, revisions, reasons and immutable atomic history', async (t) => {
  const db = new PGlite(); t.after(() => db.close());
  const admin = randomUUID(); const gm = randomUUID(); const trader = randomUUID(); const fakeGm = randomUUID();
  const stem = 'a0H000000000001AAA';
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create table public.user_profiles(id uuid primary key,active boolean,user_type text,email text,full_name text);
    create table public.collaboration_roles(user_id uuid,role text,active boolean);
    grant usage on schema public to service_role;
    grant select on public.user_profiles,public.collaboration_roles to service_role;
    alter default privileges in schema public grant all on tables to service_role;`);
  await db.query("insert into user_profiles values ($1,true,'administrator','admin@example.test','Admin'),($2,true,'general_manager','gm@example.test','GM'),($3,true,'trader','trader@example.test','Trader'),($4,true,'general_manager','othergm@example.test','Other GM')", [admin, gm, trader, fakeGm]);
  await db.query("insert into collaboration_roles values($1,'general_manager',true)", [gm]);
  const directory = new URL('../supabase/migrations/', import.meta.url);
  const filename = (await readdir(directory)).find((name) => name.endsWith('_dashboard_nom_b_policies.sql'));
  await db.exec(await readFile(new URL(filename, directory), 'utf8'));
  const save = (mode, revision, who = admin, reason = 'payment_received', note = '') => db.query('select * from save_dashboard_nom_b_policy($1,$2,$3,$4,$5,$6)', [stem, mode, reason, note, revision, who]);
  const observe = (status, waiverType, revision, at, who = trader) => db.query('select observe_dashboard_nom_b($1::jsonb,$2,$3)', [JSON.stringify([{ stemId: stem, status, waiverType, policyRevision: revision, evidence: { asOfDate: '2026-09-29', receivable: { amount: '99.99', currency: 'USD', usdEquivalent: '99.99', rate: '1', invoiceIds: ['invoice1'] } } }]), who, at]);
  await db.exec('set role service_role');
  await assert.rejects(save('waive', 0, trader), /permission/i);
  await assert.rejects(save('waive', 0, fakeGm), /permission/i);
  await assert.rejects(save('waive', 0, admin, 'other'), /reason/i);
  await assert.rejects(save('require', 0), /reason/i);
  await assert.rejects(save('waive', 0, admin, 'other', 'a'.repeat(1001)), /invalid/i);
  const first = (await save('waive', 0)).rows[0];
  assert.equal(first.revision, 1); assert.equal(first.updated_by_name, 'Admin');
  const second = (await save('waive', 1)).rows[0]; assert.equal(second.revision, 1);
  await assert.rejects(save('require', 0, gm, 'other', 'Original required'), /changed/i);
  assert.equal((await db.query('select count(*)::int n from dashboard_nom_b_events')).rows[0].n, 1);
  const required = (await save('require', 1, gm, 'other', 'Original required')).rows[0]; assert.equal(required.revision, 2);
  const automatic = (await save('automatic', 2)).rows[0]; assert.equal(automatic.revision, 3); assert.equal(automatic.reason_code, null); assert.equal(automatic.reason_text, '');
  await observe('waived', 'automatic', 3, '2026-09-29T00:00:00Z');
  await observe('waived', 'automatic', 3, '2026-09-29T00:01:00Z');
  assert.equal((await db.query("select count(*)::int n from dashboard_nom_b_events where event_type='status_changed'")).rows[0].n, 1);
  await observe('missing', null, 3, '2026-09-29T00:02:00Z');
  await observe('waived', 'automatic', 3, '2026-09-29T00:01:30Z');
  assert.equal((await db.query('select status from dashboard_nom_b_observations')).rows[0].status, 'missing');
  await assert.rejects(observe('waived', 'automatic', 2, '2026-09-29T00:03:00Z'), /changed/i);
  assert.equal((await db.query('select status from dashboard_nom_b_observations')).rows[0].status, 'missing');
  await observe('filed', null, 3, '2026-09-29T00:03:00Z');
  const races = await Promise.allSettled([save('waive', 3), save('require', 3, gm, 'other', 'Required')]);
  assert.equal(races.filter((result) => result.status === 'fulfilled').length, 1);
  assert.equal(races.filter((result) => result.status === 'rejected').length, 1);
  await assert.rejects(db.exec('update dashboard_nom_b_events set reason_text=\'rewrite\''), /permission/i);
  await assert.rejects(db.exec('delete from dashboard_nom_b_events'), /permission/i);
  await assert.rejects(db.exec('truncate dashboard_nom_b_events'), /permission/i);
  for (const role of ['anon', 'authenticated']) {
    await db.exec(`reset role;set role ${role}`);
    for (const table of ['dashboard_nom_b_policies', 'dashboard_nom_b_observations', 'dashboard_nom_b_events']) await assert.rejects(db.exec(`select * from ${table}`), /permission denied/i);
    await assert.rejects(save('waive', 4), /permission denied/i);
    await assert.rejects(observe('missing', null, 4, '2026-09-29T00:04:00Z'), /permission denied/i);
  }
  await db.exec('reset role');
  await assert.rejects(db.exec("update dashboard_nom_b_events set reason_text='rewrite'"), /append-only/i);
  await db.query('delete from user_profiles where id=$1', [admin]);
  const event = (await db.query("select actor_email,actor_user_id from dashboard_nom_b_events where event_type='policy_changed' order by created_at limit 1")).rows[0];
  assert.equal(event.actor_user_id, admin); assert.equal(event.actor_email, 'admin@example.test');
  await db.query('update user_profiles set active=false where id=$1', [gm]);
  await db.exec('set role service_role');
  await assert.rejects(save('waive', 4, gm), /permission/i);
});
