import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

test('Special Terms is a default-visible Trading page with controlled management', () => {
  const layout = read('src/components/Layout.jsx');
  const workspaces = read('src/lib/workspaceStandards.js');
  const app = read('src/App.jsx');
  const auth = read('src/lib/authModules.js');
  const functions = read('api/functions/[name].js');

  assert.match(layout, /workspaceNavigation\('buyers_administrator'[\s\S]*workspaceNavigation\('markets'[\s\S]*workspaceNavigation\('special_terms'[\s\S]*workspaceNavigation\('hedge_desk'/);
  assert.match(workspaces, /buyers_administrator:[\s\S]*title: 'Account Managers'[\s\S]*markets:[\s\S]*title: 'Markets'[\s\S]*special_terms:[\s\S]*title: 'Special Terms'[\s\S]*hedge_desk:/);
  assert.match(app, /path="\/special-terms"[\s\S]*moduleId="special_terms"/);
  assert.match(auth, /id: 'special_terms_manage'/);
  assert.match(auth, /id: 'special_terms_clause_approve'/);
  assert.match(functions, /specialTermsSave:[\s\S]*\['special_terms'\]/);
  assert.match(functions, /specialTermsTermRetire:[\s\S]*\['special_terms'\]/);
  assert.match(functions, /specialTermsPdfExport: \['special_terms'\]/);
  assert.match(functions, /requireCapability\(context\.client, context\.profile, 'special_terms_manage'/);
  assert.match(functions, /activeGeneralManager\?\.id === context\.profile\.id/);
});

test('approved Special Terms can be retired only through the guarded lifecycle', () => {
  const service = read('api/_specialTerms.js');
  const functions = read('api/functions/[name].js');
  const apex = read('force-app/main/default/classes/SpecialTermRevisionService.cls');
  const rest = read('force-app/main/default/classes/SpecialTermRevisionRest.cls');
  const statusField = read('force-app/main/default/objects/Special_Term_Revision__c/fields/Status__c.field-meta.xml');
  const enquiryLookup = read('force-app/main/default/objects/Enquiry_Special_Term__c/fields/Special_Term__c.field-meta.xml');

  assert.match(service, /term_retire: OBJECTS\.term/);
  assert.match(service, /export async function retireSpecialTerm/);
  assert.match(service, /Approval_Status__c != 'Retired'/);
  assert.match(service, /PROTECTED_TERM_REVISION_STATUSES[\s\S]*'Retired'/);
  assert.match(functions, /requireSpecialTermClauseApprover\(context\)[\s\S]*retireSpecialTerm/);
  assert.match(apex, /public static Id retireTerm/);
  assert.match(apex, /Enquiry_Special_Term__c WHERE Special_Term__c = :termId/);
  assert.match(apex, /Special_Term_Rule__c WHERE Special_Term__c = :termId/);
  assert.match(apex, /Retirement_Reason__c = retirementReason/);
  assert.match(apex, /State__c = 'Historical'/);
  assert.match(rest, /action == 'retire'/);
  assert.match(statusField, /<fullName>Retired<\/fullName>/);
  assert.match(enquiryLookup, /Special_Term__c\.Approval_Status__c[\s\S]*<operation>notEqual<\/operation>[\s\S]*<value>Retired<\/value>/);
});

test('Special Terms validates the authoritative Salesforce schema and rule lookups', () => {
  const service = read('api/_specialTerms.js');
  const salesforce = read('api/_salesforce.js');

  assert.match(service, /term: 'Special_Term__c'/);
  assert.match(service, /rule: 'Special_Term_Rule__c'/);
  assert.match(service, /clause: 'Special_Term_Clause__c'/);
  assert.match(service, /clauseVersion: 'Special_Term_Clause_Version__c'/);
  assert.match(service, /clauseAssignment: 'Special_Term_Clause_Assignment__c'/);
  assert.match(service, /'Special_Term__c', \{ referenceTo: OBJECTS\.term/);
  assert.match(service, /name === 'Clause__c' \? \{\} : \{ updateable: true \}/);
  assert.match(service, /clauseAssignment, OBJECTS\.clauseAssignment, 'Special_Term__c'.*createable: true/s);
  assert.match(service, /'Account__c', \{ referenceTo: OBJECTS\.account/);
  assert.match(service, /'Port__c', \{ referenceTo: OBJECTS\.port/);
  assert.match(service, /'Product__c', \{ referenceTo: OBJECTS\.product/);
  assert.match(service, /Inactive_Suspended__c = false/);
  assert.match(service, /IsActive = true/);
  assert.match(service, /Account WHERE Inactive_Suspended__c = false AND \(Name LIKE/);
  assert.match(service, /secondary: row\.Company_Code__c \|\| 'No CL Key'/);
  assert.match(service, /getSpecialTermForExport/);
  assert.match(service, /WHERE Id = '\$\{soql\(id\)\}' LIMIT 1/);
  assert.match(service, /Clause_Structure_Status__c/);
  assert.match(service, /Original_Terms_Text__c/);
  assert.match(service, /Confirmation_Clause_Status__c/);
  assert.match(service, /Nomination_Clause_Status__c/);
  assert.match(service, /Projection__c/);
  assert.match(service, /if \(error\?\.code !== 'SPECIAL_TERMS_SCHEMA_INVALID'\) throw error;/);
  assert.match(service, /return loadSpecialTermsSchema\(\{ force: true, write \}\);/);
  assert.match(salesforce, /DEFAULT_API_VERSION = 'v67\.0'/);
});

test('Salesforce owns priority while FCOS protects mutations and deletion', () => {
  const service = read('api/_specialTerms.js');
  const rulePayload = service.match(/function rulePayload[\s\S]*?\n\}/)?.[0] || '';

  assert.doesNotMatch(rulePayload, /Priority__c/);
  assert.match(service, /assertCurrent\(/);
  assert.match(service, /allOrNone: true/);
  assert.match(service, /Salesforce computes Priority__c only on insert/);
  assert.match(service, /referenceId: 'newRule'/);
  assert.match(service, /composite\/sobjects\?ids=/);
  assert.match(service, /confirmationName/);
  assert.match(service, /previewSpecialTermDeletion/);
  assert.match(service, /Approved, rejected, superseded, or rolled-back revision history must be retained/);
  assert.doesNotMatch(service, /sanitizeRichText/);
  assert.match(service, /special_terms_operations/);
  assert.match(service, /operation_status === 'succeeded'/);
});

test('Special Terms data is service-only and included in the Universal Audit Trail', () => {
  const migration = read('supabase/migrations/20260802110000_salesforce_special_terms.sql');
  const clauseMigration = read('supabase/migrations/20260809173753_special_term_clause_bank.sql');
  const functions = read('api/functions/[name].js');
  const page = read('src/pages/SpecialTerms.jsx');
  const editor = read('src/pages/SpecialTermEditor.jsx');
  const app = read('src/App.jsx');
  const clauseService = read('api/_specialTermClauses.js');

  assert.match(migration, /alter table public\.special_terms_operations enable row level security/);
  assert.match(migration, /revoke all on table public\.special_terms_operations from anon, authenticated/);
  assert.match(migration, /grant all on table public\.special_terms_operations to service_role/);
  assert.match(clauseMigration, /special_terms_clause_approve/);
  assert.match(clauseMigration, /Special_Term_Clause_Assignment__c/);
  assert.match(clauseMigration, /revoke all on table public\.special_terms_operations from anon, authenticated/);
  assert.match(functions, /source: 'Special Terms'/);
  assert.match(page, /specialTermsSummaryList/);
  assert.doesNotMatch(page, /specialTermsWorkspace/);
  assert.match(page, /\{ id: 'terms', label: 'Special Terms'/);
  assert.match(page, /\{ id: 'clauses', label: 'Clause Library'/);
  assert.match(page, /Update/);
  assert.match(page, /Continue/);
  assert.match(page, /Review & publish/);
  assert.match(page, /Resolve relink/);
  assert.match(app, /path="\/special-terms\/:termId"/);
  assert.match(read('src/components/special-terms/WholeTermRevisionPanel.jsx'), /Search Account name or CL Key/);
  assert.match(page, /<PageMethodology \{\.\.\.SPECIAL_TERMS_METHODOLOGY\}/);
  assert.match(page, /specialTermsDocumentExport/);
  assert.match(page, /source: 'live'/);
  assert.match(page, /download\(term, 'pdf'\)/);
  assert.match(page, /download\(term, 'docx'\)/);
  assert.match(functions, /specialTermsDocumentExport/);
  assert.match(functions, /Saved drafts may be downloaded as watermarked PDF only/);
  assert.match(functions, /special_terms_document_exported/);
  assert.match(functions, /outcome: 'success'/);
  assert.match(editor, /<WholeTermRevisionPanel/);
  assert.match(page, /<MigrationBatchPanel/);
  assert.match(page, /summary\?\.canDraft/);
  assert.match(page, /Migration queue/);
  assert.match(page, /<ClauseBankPanel/);
  const projectionSection = read('src/components/special-terms/ClauseProjectionSection.jsx');
  assert.match(projectionSection, /<ClauseComposer/);
  assert.match(projectionSection, /<MigrationReviewPanel/);
  assert.match(projectionSection, /wholeTermRevision/);
  const revisionPanel = read('src/components/special-terms/WholeTermRevisionPanel.jsx');
  assert.match(revisionPanel, /specialTermRevisionCommit/);
  assert.match(revisionPanel, /specialTermRevisionRollback/);
  assert.match(revisionPanel, /specialTermsDocumentExport/);
  assert.match(revisionPanel, /source: mode/);
  assert.match(revisionPanel, /expectedRevisionLastModifiedAt/);
  assert.doesNotMatch(revisionPanel, /Start whole-term draft/);
  assert.match(revisionPanel, /Complete Special Term update/);
  assert.match(revisionPanel, /Submit for approval/);
  assert.match(revisionPanel, /Approve &amp; publish/);
  assert.match(revisionPanel, /specialTermMigrationPreviewAll/);
  const previewModel = read('src/lib/specialTermDocumentPreview.js');
  const preview = read('src/components/special-terms/SpecialTermDocumentPreview.jsx');
  assert.match(previewModel, /revision\.projections\.termsText/);
  assert.doesNotMatch(previewModel, /confirmationRemark: text/);
  assert.doesNotMatch(previewModel, /nominationRemark: text/);
  assert.match(preview, /SPECIAL TERMS/i);
  assert.match(preview, /Page \{pageIndex \+ 1\} of \{pageCount\}/);
  assert.match(preview, /Fit width/);
  assert.match(preview, /SPECIAL_TERMS_DOCUMENT_TOKENS\.list\.markerRightMm/);
  assert.match(preview, /SPECIAL_TERMS_DOCUMENT_TOKENS\.list\.textIndentMm/);
  assert.match(preview, /SPECIAL_TERMS_DOCUMENT_TOKENS\.list\.nestedTextIndentMm/);
  assert.match(preview, /Word is editable; Salesforce remains authoritative\. Attachments are PDF-only\./);
  assert.match(preview, /if \(!hasLiveTerms && !hasDraftTerms\) return null/);
  assert.doesNotMatch(preview, /No Terms Text clauses\./);
  assert.match(revisionPanel, /hasTermsDocument/);
  assert.match(revisionPanel, /\.\.\.\(hasTermsDocument \? \[\['preview', 'Preview'\]\] : \[\]\)/);
  const batchPanel = read('src/components/special-terms/MigrationBatchPanel.jsx');
  assert.match(batchPanel, /specialTermMigrationBatchList/);
  assert.match(batchPanel, /At most 20 related terms per batch/);
  assert.match(batchPanel, /Manual segmentation/);
  const clauseBank = read('src/components/special-terms/ClauseBankPanel.jsx');
  const workflow = read('src/lib/specialTermsWorkflow.js');
  assert.match(clauseBank, /CLAUSE_BANK_VIEWS/);
  assert.match(clauseBank, /Work Queue|work/);
  assert.match(clauseBank, /Rapid review/);
  assert.match(clauseBank, /contentVisibility: 'auto'/);
  assert.match(clauseBank, /limit: PAGE_SIZE/);
  assert.match(clauseBank, /Drafting-quality check/);
  assert.match(clauseBank, /Governed history/);
  assert.match(clauseBank, /Duplicate review/);
  assert.match(clauseBank, /sessionStorage/);
  assert.match(workflow, /Needs wording review/);
  assert.match(workflow, /Blocked by assignment/);
  assert.match(clauseBank, /approvalPending/);
  assert.match(clauseBank, /draftSavePending/);
  assert.match(clauseBank, /setClauses\(\(current\) => current\.map/);
  assert.match(clauseBank, /window\.scrollTo\(\{ \.\.\.viewport, behavior: 'auto' \}\)/);
  assert.match(clauseBank, /focus\(\{ preventScroll: true \}\)/);
  assert.doesNotMatch(clauseBank.match(/const approveClause = async[\s\S]*?\n  };/)?.[0] || '', /load\(true\)|onChanged/);
  const saveDraft = clauseBank.match(/const saveDraft = async[\s\S]*?\n  };/)?.[0] || '';
  assert.match(saveDraft, /specialTermClauseDraftSave/);
  assert.match(saveDraft, /setClauses\(\(current\)/);
  assert.match(saveDraft, /setDraftSavePending/);
  assert.match(saveDraft, /window\.scrollTo\(\{ \.\.\.viewport, behavior: 'auto' \}\)/);
  assert.match(saveDraft, /focus\(\{ preventScroll: true \}\)/);
  assert.doesNotMatch(saveDraft, /load\(true\)|onChanged|setBusy/);
  assert.match(clauseService, /finishClauseDraftOperation/);
  assert.match(clauseService, /clause: replayClauseId \? await loadOneClause/);
  const composer = read('src/components/special-terms/ClauseComposer.jsx');
  assert.match(composer, /New use is allowed but will require a governed relink/);
  const consolidationQueue = read('src/components/special-terms/ClauseConsolidationQueue.jsx');
  assert.match(consolidationQueue, /specialTermClauseConsolidationRelink/);
  assert.match(consolidationQueue, /Complete retirement/);
  assert.match(consolidationQueue, /Live wording remains unchanged/);
  assert.match(consolidationQueue, /term\.revisionState !== 'Awaiting Approval'/);
  assert.match(page, /<MigrationInventoryPanel/);
  assert.doesNotMatch(page, /<SpecialTermReadinessPanel/);
  assert.doesNotMatch(page, /specialTermEditorValue\(termForm\.termsText\)/);
  assert.match(clauseService, /compileClauseList/);
  assert.match(clauseService, /Confirmation Remark/);
  assert.match(clauseService, /Nomination Remark/);
  assert.match(clauseService, /Account__c,Account__r\.Name,Account__r\.Company_Code__c,Port__c,Port__r\.Name,Port__r\.Country__c,Product__c,Product__r\.Name/);
  assert.match(clauseService, /rules: liveRuleResult\.records\.map\(mapDetailRule\)/);
  assert.match(clauseService, /allOrNone: true/);
  assert.match(clauseService, /composite\/graph/);
  assert.match(clauseService, /upgradeAvailable/);
  assert.match(clauseService, /selectedClauseVersionId/);
  assert.match(clauseService, /hasMaterialDifference/);
  assert.doesNotMatch(clauseMigration, /Clause_Text__c|Terms_Text__c/);
  assert.doesNotMatch(page, /view: activeTab,[\s\S]*search: search\.trim\(\)/);
  assert.match(page, /Type \{deleteTarget\.preview\.confirmationLabel\}/);
  assert.match(page, /specialTermDeletePreview/);
  assert.match(page, /setSummary\(\(current\).*terms: current\.terms\.filter/s);
  assert.match(clauseBank, /specialTermClauseDelete/);
  assert.match(clauseBank, /specialTermClauseDraftDiscard/);
  assert.match(clauseBank, /Delete Legacy Draft/);
  assert.match(clauseBank, /Discard Draft/);
  assert.doesNotMatch(clauseBank.match(/const submitDeletion = async[\s\S]*?\n  };/)?.[0] || '', /load\(true\)|onChanged/);
  assert.doesNotMatch(page, /termForm\?\.termsText\.trim\(\)\.length < 3/);
});

test('Special Terms owns the Salesforce response metadata used by its status bar', () => {
  const page = read('src/pages/SpecialTerms.jsx');
  const component = page.split('export default function SpecialTerms()')[1] || '';
  const stateDeclaration = component.indexOf('const [responseMeta, setResponseMeta] = useState(null);');
  const loadCallback = component.indexOf('const load = useCallback');

  assert.ok(stateDeclaration >= 0, 'Special Terms must declare response metadata in the page component');
  assert.ok(stateDeclaration < loadCallback, 'response metadata state must be in scope for the load callback');
});

test('System Health exposes redacted Special-Term migration readiness', () => {
  const handler = read('api/functions/[name].js');
  assert.match(handler, /async function specialTermsMigrationHealthRow/);
  assert.match(handler, /Special-Term Clause Migration/);
  assert.match(handler, /aiDraftingConfigured: Boolean\(process\.env\.OPENAI_API_KEY\)/);
  assert.match(handler, /cachedHealthCheck\('special-terms-migration'/);
  assert.doesNotMatch(handler, /specialTermsMigrationHealthRow[\s\S]{0,2500}Clause_Text__c/);
});
