function policy({ mutation, cache = 'none', externalAction = false, capability = null }) {
  return Object.freeze({
    mutation,
    cache,
    externalAction,
    capability,
    audit: mutation || externalAction ? 'required' : 'none',
  });
}

function readPolicy(options = {}) {
  return policy({ ...options, mutation: false });
}

function mutationPolicy(options = {}) {
  return policy({ ...options, mutation: true });
}

const HANDLER_BEHAVIOR = Object.freeze({
  authContext: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  portalApplicationsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  portalApplicationLaunch: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  portalSignOut: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  portalEntitlementSyncCron: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  collaborationList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationCreate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationUpdate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationBulkUpdate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationFollowerToggle: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationDependencySave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationDependencyRemove: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationMilestoneSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationTemplateList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationTemplateSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationArchive: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationCommentSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationCommentDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationAttachmentPrepare: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationAttachmentComplete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationAttachmentUrl: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationAttachmentDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationNotificationsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationNotificationsRead: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  collaborationDailyCron: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementCreate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementPropose: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementDecision: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementAttachmentPrepare: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementAttachmentComplete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementAttachmentUrl: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  improvementAttachmentDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  workNotificationsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  workNotificationsRead: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  workNotificationsState: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  systemErrorVerify: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  workCommitmentsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  navigationPreferencesGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  navigationPreferencesSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  navigationPreferencesReset: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  workspacePreferencesGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  workspacePreferencesSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterBackgroundSync: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterLeave: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterLeaveSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterDirectory: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterDirectoryRefresh: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterPresets: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterAction: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterActionStatus: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterUndo: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterRetry: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterFilingRetry: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterAttachmentUrl: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterAdvisor: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterSettings: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailRouterOutbox: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterDelta: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterSubscription: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  emailRouterMaintenanceCron: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  hedgeDeskEntity: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeMarkets: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskParseMops: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskGenerateInvoice: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskSaveInvoicePdf: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskSendInvoiceEmail: mutationPolicy({"cache":"none","externalAction":true,"capability":"hedge_settlement_manage"}),
  hedgeDeskSfsReport: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskSfsFile: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskSfsSend: mutationPolicy({"cache":"none","externalAction":true,"capability":"hedge_close_approve"}),
  hedgeDeskSalesforcePush: mutationPolicy({"cache":"none","externalAction":true,"capability":"hedge_book_manage"}),
  hedgeDeskSalesforcePreview: readPolicy({"cache":"none","externalAction":false,"capability":"hedge_book_manage"}),
  hedgeDeskSalesforceMapping: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskAssistant: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskAssistantSettings: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  hedgeDeskMaintenanceCron: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermsWorkspace: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  specialTermsPdfExport: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermsDocumentExport: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermsOptions: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermClauseBank: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  specialTermMigrationInventory: readPolicy({"cache":"none","externalAction":false,"capability":"special_terms_clause_approve"}),
  specialTermClauseDraftSave: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermClauseApprove: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermClauseRetire: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermCompositionSave: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermMigrationPreview: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermMigrationSave: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermMigrationActivate: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermMigrationRollback: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermRevisionSave: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermRevisionApprove: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermRevisionRollback: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_clause_approve"}),
  specialTermMigrationBatchList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermApprovalQueue: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  specialTermClauseAiDraft: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  specialTermsSave: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_manage"}),
  specialTermsDelete: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_manage"}),
  specialTermRuleSave: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_manage"}),
  specialTermRuleDelete: mutationPolicy({"cache":"none","externalAction":true,"capability":"special_terms_manage"}),
  paymentCollectionsReconcileCron: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthReportingLinesList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthReportingLineSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthReportingLinesSaveBatch: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthCoachingBootstrap: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthPlanSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthPlanCloseout: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalSubmit: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalDecision: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalProgressSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalCompletion: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalEvidenceOptions: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthGoalEvidenceSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingRelationshipInvite: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingRelationshipRespond: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingRelationshipEnd: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingSessionSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingSessionContentSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingSessionConfirm: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingSessionCancel: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingActionSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingActionPublish: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingActionProposalRespond: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthAttachmentPrepare: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthAttachmentComplete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthAttachmentUrl: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  growthEmailPreferencesSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  coachingCalendarResolve: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  coachingCalendarRetry: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  growthCoachingDailyCron: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  salesforceDashboard: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceDashboardFiltered: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  dashboardAccountInsight: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  dashboardAccountInsightExport: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceTopBuyers: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceStemDetail: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceStemDocuments: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceDocumentDownload: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  unofficialCompensationList: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  unofficialCompensationOptions: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  unofficialCompensationClaimCreate: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  unofficialCompensationClaimGroupStatus: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  unofficialCompensationRecoveryCreate: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  unofficialCompensationRecoveryDelete: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  exceptionReviewWorkflowList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  exceptionReviewWorkflowSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceDisputeStems: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaSaveDraft: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaSubmitApproval: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaApprove: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaReject: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaMarkExecuted: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeBetaClose: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowSaveDraft: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowSubmitApproval: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowApprove: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowReject: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowAccountingUpdate: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowSupplierInstructionUpdate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowSupplierOffsetOptions: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowSupplierAmountAmend: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowUploadDocument: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowDocuments: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowMarkExecuted: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowClose: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  disputeWorkflowCompensationClaims: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowCompensationClaimLink: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  disputeWorkflowAcceptExternalClosure: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceBuyerInvoicesDue: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  buyerInvoiceCollectionList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceCollectionSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceCollectionEventCreate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoicePaymentAdviceSave: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  paymentCollectionsReconcile: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  shipAgentChargesList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  shipAgentChargesDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  shipAgentChargesOptions: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  shipAgentChargesSaveConfirm: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  shipAgentChargesGmOverride: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  shipAgentChargesPostInvoiceResolve: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  shipAgentChargesSync: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoicePostingReminderOverrideSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceEmailSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceEmailSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":"financial_report_settings_manage"}),
  buyerInvoiceReminderRulesList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceReminderRuleSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoiceReminderRuleRemove: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoicePaymentReminderPrepare: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyerInvoicePaymentReminderSend: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  outstandingBuyerInvoicesEmailReport: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  outstandingBuyerInvoicesEmailCron: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  incomingPaymentsList: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  incomingPaymentEmailSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  incomingPaymentEmailSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":"financial_report_settings_manage"}),
  incomingPaymentInterestSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  incomingPaymentInterestSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":"financial_report_settings_manage"}),
  incomingPaymentEmailReport: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  incomingPaymentInterestInvoiceRequest: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  incomingPaymentSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  incomingPaymentSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":"financial_report_settings_manage"}),
  incomingPaymentAllocationConfirm: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  cashflowForecast: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  cashflowBuyerPaymentPerformance: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  cashflowSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  cashflowSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  cashflowHolidayCalendar: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  stemPnl: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceBrokerRegister: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  frankfurterUsdCnyRate: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  brokerCommissionSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  brokerCommissionSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":"broker_settings_manage"}),
  reportExportCreate: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  reportExportsList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  reportExportRename: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  reportExportDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  reportExportDownload: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyersAdministratorList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  buyersAdministratorSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  accountManagersList: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  accountManagersSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  accountManagersSaveNote: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  accountManagersRetrySync: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailSenderStatus: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailSenderMailboxSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  emailSenderRouteSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  systemHealth: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  dashboardAiSettingsGet: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  dashboardAiSettingsSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  dashboardAiSearch: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  backboneBridgeIdentity: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  backboneTradeProjection: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  backboneFinanceHandoffs: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  backboneFinanceHandoffDetail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceSchema: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceObjectFields: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  salesforceFullSchema: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  dashboardFilterOptions: readPolicy({"cache":"server","externalAction":false,"capability":null}),
  salesforceDescribeChildren: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminUsersList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminAuditLogs: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminUserSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminPortalAccessSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminPortalAccessRetry: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminPortalApplicationsHealth: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminUserDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminUserTypeSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminUserTypeDelete: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdatesList: readPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdatesSync: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateItemSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateBatchSave: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateBatchCancel: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateItemSkip: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateItemRestore: mutationPolicy({"cache":"none","externalAction":false,"capability":null}),
  adminFcosUpdateBatchSend: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  adminFcosUpdateDeliveryRetry: mutationPolicy({"cache":"none","externalAction":true,"capability":null}),
  universalAuditTrail: readPolicy({"cache":"none","externalAction":false,"capability":null}),
});

export function buildHandlerPolicyRegistry(moduleAccess, authExemptHandlers = new Set()) {
  const accessNames = Object.keys(moduleAccess || {});
  const behaviorNames = Object.keys(HANDLER_BEHAVIOR);
  const missingBehavior = accessNames.filter((name) => !HANDLER_BEHAVIOR[name]);
  const orphanBehavior = behaviorNames.filter((name) => !Object.prototype.hasOwnProperty.call(moduleAccess, name));
  if (missingBehavior.length || orphanBehavior.length) {
    throw new Error(`FCOS handler policy registry mismatch. Missing: ${missingBehavior.join(', ') || 'none'}; orphaned: ${orphanBehavior.join(', ') || 'none'}.`);
  }
  return Object.freeze(Object.fromEntries(accessNames.map((name) => [name, Object.freeze({
    ...HANDLER_BEHAVIOR[name],
    modules: Object.freeze([...(moduleAccess[name] || [])]),
    authentication: authExemptHandlers.has(name) ? 'cron' : 'active_user',
  })])));
}

export function handlerPolicyFor(registry, name) {
  return Object.prototype.hasOwnProperty.call(registry || {}, name) ? registry[name] : null;
}

export function registeredHandlerBehavior(name) {
  return Object.prototype.hasOwnProperty.call(HANDLER_BEHAVIOR, name) ? HANDLER_BEHAVIOR[name] : null;
}

export function registeredHandlerCapabilities() {
  return [...new Set(Object.values(HANDLER_BEHAVIOR).map((entry) => entry.capability).filter(Boolean))];
}
