import { jsPDF } from 'jspdf'

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function number(value) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : 0
}

function money(value) {
  const amount = number(value)
  return `${amount < 0 ? '-' : ''}$${Math.abs(amount).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`
}

function monthLabel(value) {
  const [year, month] = String(value || '').split('-')
  return year && month ? `${MONTHS[Number(month) - 1] || month} ${year}` : String(value || '-')
}

function dateLabel(value) {
  if (!value) return '-'
  const [year, month, day] = String(value).slice(0, 10).split('-')
  return year && month && day ? `${day}/${month}/${year}` : String(value)
}

function csvCell(value) {
  return `"${String(value ?? '').replaceAll('"', '""')}"`
}

export function sfsReportFilename(month, revision, extension) {
  return `SFS_Realised_PnL_${month}_R${revision || 1}.${extension}`
}

export function generateSfsReportCsv(report, { revision = 1, status = 'provisional' } = {}) {
  const headers = [
    'Report Month',
    'Revision',
    'Status',
    'Trade ID',
    'Trade Date',
    'Leg',
    'Product',
    'Direction',
    'Contract Month',
    'Quantity',
    'Unit',
    'Normalized Quantity',
    'Trade Price',
    'Pricing Basis',
    'Balance Start Date',
    'Final MOPS',
    'Gross P&L',
    'SFS Commission',
    'ICE Exchange Fee',
    'ICE Clearing Fee',
    'ICE Settlement Fee',
    'Total Fees',
    'Net Realised P&L',
  ]
  const rows = (report.lines || []).map((line) => [
    report.month,
    revision,
    status,
    line.swapId,
    line.tradeDate,
    line.leg || '',
    line.product,
    line.direction,
    line.contractMonth,
    line.quantity,
    line.unit,
    line.normalizedQuantity,
    line.tradePrice,
    line.pricingBasis,
    line.balanceStartDate || '',
    line.settlementMops ?? '',
    line.grossPnl,
    line.fees?.sfsCommission,
    line.fees?.iceExchange,
    line.fees?.iceClearing,
    line.fees?.iceSettlement,
    line.fees?.total,
    line.netPnl,
  ])
  const totals = report.totals || {}
  const totalRow = [
    report.month,
    revision,
    status,
    'TOTAL',
    '',
    '',
    '',
    '',
    report.month,
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    totals.grossPnl,
    totals.sfsCommission,
    totals.iceExchange,
    totals.iceClearing,
    totals.iceSettlement,
    totals.totalFees,
    totals.netPnl,
  ]
  return `\uFEFF${[headers, ...rows, totalRow].map((row) => row.map(csvCell).join(',')).join('\r\n')}\r\n`
}

export function generateSfsReportPdfBuffer(report, {
  revision = 1,
  status = 'provisional',
  finalizedAt = null,
} = {}) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const width = 297
  const margin = 12
  const right = width - margin
  const dark = [32, 42, 52]
  const muted = [95, 107, 118]
  const red = [180, 30, 30]
  const light = [238, 241, 244]
  let y = 12

  const footer = () => {
    doc.setDrawColor(...light)
    doc.line(margin, 198, right, 198)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.8)
    doc.setTextColor(...muted)
    doc.text('Fratelli Cosulich Bunkers (HK) Ltd | SFS monthly realised swap P&L | Generated by FC Hedge Desk', width / 2, 202, { align: 'center' })
  }

  const newPage = () => {
    footer()
    doc.addPage()
    y = 13
  }

  doc.setFillColor(...red)
  doc.rect(0, 0, width, 10, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...dark)
  doc.text('SFS MONTHLY REALISED SWAP P&L', margin, 21)
  doc.setFontSize(9)
  doc.setTextColor(...muted)
  doc.text(`${monthLabel(report.month)} | Revision ${revision} | ${String(status).replaceAll('_', ' ').toUpperCase()}`, margin, 28)
  doc.text(`Recipient: ${report.recipient || 'accounts@cosulich.com.hk'}`, right, 21, { align: 'right' })
  doc.text(`Finalized: ${finalizedAt ? new Date(finalizedAt).toLocaleString('en-GB', { timeZone: 'Asia/Hong_Kong' }) + ' HKT' : 'Provisional preview'}`, right, 28, { align: 'right' })

  y = 38
  const metrics = [
    ['Gross realised P&L', report.totals?.grossPnl],
    ['SFS commission', -number(report.totals?.sfsCommission)],
    ['ICE exchange', -number(report.totals?.iceExchange)],
    ['ICE clearing', -number(report.totals?.iceClearing)],
    ['ICE settlement', -number(report.totals?.iceSettlement)],
    ['Net realised P&L', report.totals?.netPnl],
  ]
  const metricWidth = (right - margin) / metrics.length
  metrics.forEach(([label, value], index) => {
    const x = margin + index * metricWidth
    doc.setFillColor(...light)
    doc.roundedRect(x, y, metricWidth - 2, 18, 1.5, 1.5, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.8)
    doc.setTextColor(...muted)
    doc.text(label.toUpperCase(), x + 3, y + 5.5)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...dark)
    doc.text(money(value), x + 3, y + 13)
  })

  y += 27
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.2)
  doc.setTextColor(...muted)
  const completion = report.completeness || {}
  const sourceDates = (report.source?.records || []).map((row) => row.priceDate).filter(Boolean)
  doc.text(
    `MOPS source: ${report.source?.name || 'S&P Global Platts Singapore MOPS'} | Complete actual publications: ${completion.actual || 0}/${completion.total || 0} | ${sourceDates.length ? `${dateLabel(sourceDates[0])} to ${dateLabel(sourceDates.at(-1))}` : 'No publication records'}`,
    margin,
    y,
  )
  y += 7

  const columns = [
    { key: 'tradeDate', label: 'TRADE', x: margin, width: 17 },
    { key: 'product', label: 'PRODUCT', x: margin + 18, width: 15 },
    { key: 'direction', label: 'SIDE', x: margin + 34, width: 13 },
    { key: 'quantity', label: 'QUANTITY', x: margin + 48, width: 24 },
    { key: 'tradePrice', label: 'TRADE PX', x: margin + 73, width: 20 },
    { key: 'settlementMops', label: 'FINAL MOPS', x: margin + 94, width: 22 },
    { key: 'grossPnl', label: 'GROSS P&L', x: margin + 117, width: 27 },
    { key: 'sfs', label: 'SFS', x: margin + 145, width: 21 },
    { key: 'exchange', label: 'EXCHANGE', x: margin + 167, width: 22 },
    { key: 'clearing', label: 'CLEARING', x: margin + 190, width: 22 },
    { key: 'settlement', label: 'SETTLEMENT', x: margin + 213, width: 23 },
    { key: 'netPnl', label: 'NET P&L', x: margin + 237, width: 35 },
  ]

  const drawHeader = () => {
    doc.setFillColor(...dark)
    doc.rect(margin, y - 4, right - margin, 8, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(255, 255, 255)
    columns.forEach((column) => doc.text(column.label, column.x + 1, y + 1))
    y += 6
  }
  drawHeader()

  const valuesFor = (line) => ({
    tradeDate: dateLabel(line.tradeDate),
    product: line.product,
    direction: `${line.direction}${line.leg ? ` L${line.leg}` : ''}`,
    quantity: `${number(line.quantity).toLocaleString('en-US', { maximumFractionDigits: 2 })} ${line.unit || ''}`,
    tradePrice: number(line.tradePrice).toFixed(3),
    settlementMops: line.settlementMops == null ? '-' : number(line.settlementMops).toFixed(3),
    grossPnl: money(line.grossPnl),
    sfs: money(-number(line.fees?.sfsCommission)),
    exchange: money(-number(line.fees?.iceExchange)),
    clearing: money(-number(line.fees?.iceClearing)),
    settlement: money(-number(line.fees?.iceSettlement)),
    netPnl: money(line.netPnl),
  })

  ;(report.lines || []).forEach((line, index) => {
    if (y > 187) {
      newPage()
      drawHeader()
    }
    if (index % 2 === 0) {
      doc.setFillColor(248, 249, 250)
      doc.rect(margin, y - 4, right - margin, 7, 'F')
    }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.7)
    doc.setTextColor(...dark)
    const values = valuesFor(line)
    columns.forEach((column) => {
      const value = String(values[column.key] ?? '')
      doc.text(value, column.x + 1, y, { maxWidth: column.width - 2 })
    })
    y += 7
  })

  if (!(report.lines || []).length) {
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(...muted)
    doc.text('No SFS-cleared swap legs belong to this contract month.', margin + 2, y + 3)
    y += 10
  }

  if (y > 165) newPage()
  y += 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...dark)
  doc.text('MOPS INPUT APPENDIX', margin, y)
  y += 7
  const sourceColumns = [
    { key: 'date', label: 'PUBLICATION DATE', x: margin, width: 35 },
    { key: 'source', label: 'SOURCE', x: margin + 37, width: 84 },
    { key: 's380', label: 'S380', x: margin + 123, width: 30 },
    { key: 's05', label: 'S0.5', x: margin + 155, width: 30 },
    { key: 'sgo', label: 'SGO', x: margin + 187, width: 30 },
    { key: 'updated', label: 'LAST UPDATED', x: margin + 219, width: 53 },
  ]
  const drawSourceHeader = () => {
    doc.setFillColor(...dark)
    doc.rect(margin, y - 4, right - margin, 8, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(255, 255, 255)
    sourceColumns.forEach((column) => doc.text(column.label, column.x + 1, y + 1))
    y += 6
  }
  drawSourceHeader()
  ;(report.source?.records || []).forEach((row, index) => {
    if (y > 187) {
      newPage()
      drawSourceHeader()
    }
    if (index % 2 === 0) {
      doc.setFillColor(248, 249, 250)
      doc.rect(margin, y - 4, right - margin, 7, 'F')
    }
    const sourceValues = {
      date: dateLabel(row.priceDate),
      source: row.source || 'Manual',
      s380: row.s380 == null ? '-' : number(row.s380).toFixed(3),
      s05: row.s05 == null ? '-' : number(row.s05).toFixed(3),
      sgo: row.sgo == null ? '-' : number(row.sgo).toFixed(3),
      updated: row.updatedAt ? new Date(row.updatedAt).toLocaleString('en-GB', { timeZone: 'Asia/Hong_Kong' }) : '-',
    }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.7)
    doc.setTextColor(...dark)
    sourceColumns.forEach((column) => doc.text(String(sourceValues[column.key]), column.x + 1, y, { maxWidth: column.width - 2 }))
    y += 7
  })

  footer()
  return Buffer.from(doc.output('arraybuffer'))
}
